UltimaLive: ClientRedirections Class Reference
ClientRedirections Class Reference
ClientsRedirections contains redirected client functions.
#include <ClientRedirections.h>
Static Public Member Functions
static HANDLE WINAPI OnCreateFileARunOnce (__in LPCSTR lpFileName, __in DWORD dwDesiredAccess, __in DWORD dwShareMode, __in_opt LPSECURITY_ATTRIBUTES lpSecurityAttributes, __in DWORD dwCreationDisposition, __in DWORD dwFlagsAndAttributes, __in_opt HANDLE hTemplateFile)
This function is hooked into the client by the Igrping.dll's main function. It executes once and calls the startup of UltimaLive. UltimaLive in turn rehooks this function with the permanent one.
static bool InstallClientHooks ()
Installs function hooks into the client to redirect client functions to ClientRedirections functions.
static void OnUpdateStaticBlocks ()
This function adds a mutex around the updates static blocks function in the client to avoid issues caused by the client calling this function at the same time as UltimaLive.
Static Private Member Functions
static HANDLE WINAPI OnCreateFileA (__in LPCSTR lpFileName, __in DWORD dwDesiredAccess, __in DWORD dwShareMode, __in_opt LPSECURITY_ATTRIBUTES lpSecurityAttributes, __in DWORD dwCreationDisposition, __in DWORD dwFlagsAndAttributes, __in_opt HANDLE hTemplateFile)
This function is hooked by UltimaLive's startup function. It relays the CreateFileA function to the UltimaLive file manager, which in turn relays it to any UltimaLive subscribers to process before optionally calling the original function.
static LPVOID WINAPI OnMapViewOfFile (__in HANDLE hFileMappingObject, __in DWORD dwDesiredAccess, __in DWORD dwFileOffsetHigh, __in DWORD dwFileOffsetLow, __in SIZE_T dwNumberOfBytesToMap)
static HANDLE WINAPI OnCreateFileMappingA (__in HANDLE hFile, __in_opt LPSECURITY_ATTRIBUTES lpAttributes, __in DWORD flProtect, __in DWORD dwMaximumSizeHigh, __in DWORD dwMaximumSizeLow, __in_opt LPCSTR lpName)
This method is hooked into the client's CreateFileMapping function. It redirects control to one of UltimaLive's concrete FileManager classes.
static int WINAPI OnMessageBox (_In_opt_ HWND hWnd, _In_opt_ LPCTSTR lpText, _In_opt_ LPCTSTR lpCaption, _In_ UINT uType)
This method is hooked into the client's MessageBox function.
static BOOL WINAPI OnCloseHandle (_In_ HANDLE hObject)
This method is hooked into the client's CloseHandle function. It redirects control to one of UltimaLive's concrete FileManager classes.
static void __fastcall OnReceivePacket (void *This, void *edx, unsigned char *pBuffer)
This function is called in place of the client's network receive function. It passes control to the UltimaLive network manager which gives its subscribers the chance to alter/process each network packet before the client. It then calls the clients receive function.
static int __fastcall OnSendPacket (void *This, void *edx, unsigned char *pBuffer)
This function is called in place of the client's network send function. It passes control to the UltimaLive network manager which gives its subscribers the chance to alter/process each network packet before they are sent to the server. It then calls the clients receive function.
Static Private Attributes
static HANDLE g_UpdateStaticBlocksMutex = CreateMutex(NULL, false, NULL)
Mutex for the redirected UpdateStaticBlocksMutex function.
Detailed Description
ClientsRedirections contains redirected client functions.
Definition at line 40 of file ClientRedirections.h.
Member Function Documentation
InstallClientHooks()
bool ClientRedirections::InstallClientHooks () static
Installs function hooks into the client to redirect client functions to ClientRedirections functions.
Returns
true if successful
Definition at line 33 of file ClientRedirections.cpp.
References Logger::g_pLogger, UltimaLive::g_pUltimaLive, g_UpdateStaticBlocksMutex, Utils::GetCurrentModuleName(), Logger::LogPrint(), Logger::LogPrintTaskStatusResult(), Logger::LogPrintWithoutDate(), OnCloseHandle(), OnCreateFileA(), OnCreateFileMappingA(), OnMapViewOfFile(), OnMessageBox(), OnReceivePacket(), OnSendPacket(), and OnUpdateStaticBlocks().
Referenced by UltimaLive::Start().
OnCloseHandle()
BOOL WINAPI ClientRedirections::OnCloseHandle (_In_ HANDLE hObject) static private
This method is hooked into the client's CloseHandle function. It redirects control to one of UltimaLive's concrete FileManager classes.
Parameters
hObject A valid handle to an open object.
Returns
If the function succeeds, the return value is nonzero.
Definition at line 374 of file ClientRedirections.cpp.
References UltimaLive::g_pUltimaLive, Client::GetFileManager(), UltimaLive::m_pClient, and BaseFileManager::OnCloseHandle().
Referenced by InstallClientHooks().
OnCreateFileA()
HANDLE WINAPI ClientRedirections::OnCreateFileA (__in LPCSTR lpFileName, __in DWORD dwDesiredAccess, __in DWORD dwShareMode, __in_opt LPSECURITY_ATTRIBUTES lpSecurityAttributes, __in DWORD dwCreationDisposition, __in DWORD dwFlagsAndAttributes, __in_opt HANDLE hTemplateFile) static private
This function is hooked by UltimaLive's startup function. It relays the CreateFileA function to the UltimaLive file manager, which in turn relays it to any UltimaLive subscribers to process before optionally calling the original function.
Parameters
lpFileName The name of the file or device to be created or opened.
dwDesiredAccess The requested access to the file or device, which can be summarized as read, write, both or neither.
dwShareMode The requested sharing mode of the file or device, which can be read, write, both, delete, all of these, or none.
lpSecurityAttributes A pointer to a SECURITY_ATTRIBUTES structure that contains two separate but related data members.
dwCreationDisposition An action to take on a file or device that exists or does not exist.
dwFlagsAndAttributes The file or device attributes and flags, FILE_ATTRIBUTE_NORMAL being the most common default value for files.
hTemplateFile A valid handle to a template file with the GENERIC_READ access right.
Returns
New File's Handle
Definition at line 257 of file ClientRedirections.cpp.
References UltimaLive::g_pUltimaLive, Client::GetFileManager(), UltimaLive::m_pClient, and BaseFileManager::OnCreateFileA().
Referenced by InstallClientHooks().
OnCreateFileARunOnce()
HANDLE WINAPI ClientRedirections::OnCreateFileARunOnce (__in LPCSTR lpFileName, __in DWORD dwDesiredAccess, __in DWORD dwShareMode, __in_opt LPSECURITY_ATTRIBUTES lpSecurityAttributes, __in DWORD dwCreationDisposition, __in DWORD dwFlagsAndAttributes, __in_opt HANDLE hTemplateFile) static
This function is hooked into the client by the Igrping.dll's main function. It executes once and calls the startup of UltimaLive. UltimaLive in turn rehooks this function with the permanent one.
Parameters
lpFileName The name of the file or device to be created or opened.
dwDesiredAccess The requested access to the file or device, which can be summarized as read, write, both or neither.
dwShareMode The requested sharing mode of the file or device, which can be read, write, both, delete, all of these, or none.
lpSecurityAttributes A pointer to a SECURITY_ATTRIBUTES structure that contains two separate but related data members.
dwCreationDisposition An action to take on a file or device that exists or does not exist.
dwFlagsAndAttributes The file or device attributes and flags, FILE_ATTRIBUTE_NORMAL being the most common default value for files.
hTemplateFile A valid handle to a template file with the GENERIC_READ access right.
Returns
New File's Handle
Definition at line 220 of file ClientRedirections.cpp.
References UltimaLive::g_pUltimaLive, Client::GetFileManager(), UltimaLive::m_pClient, BaseFileManager::OnCreateFileA(), and UltimaLive::Start().
OnCreateFileMappingA()
HANDLE WINAPI ClientRedirections::OnCreateFileMappingA (__in HANDLE hFile, __in_opt LPSECURITY_ATTRIBUTES lpAttributes, __in DWORD flProtect, __in DWORD dwMaximumSizeHigh, __in DWORD dwMaximumSizeLow, __in_opt LPCSTR lpName) static private
This method is hooked into the client's CreateFileMapping function. It redirects control to one of UltimaLive's concrete FileManager classes.
Parameters
hFile A handle to the file from which to create a file mapping object.
lpAttributes A pointer to a SECURITY_ATTRIBUTES structure that determines whether a returned handle can be inherited by child processes.
flProtect Specifies the page protection of the file mapping object.
dwMaximumSizeHigh The high-order DWORD of the maximum size of the file mapping object.
dwMaximumSizeLow The low-order DWORD of the maximum size of the file mapping object.
lpName The name of the file mapping object.
Returns
If the function succeeds, the return value is a handle to the newly created file mapping object.
Definition at line 347 of file ClientRedirections.cpp.
References UltimaLive::g_pUltimaLive, Client::GetFileManager(), UltimaLive::m_pClient, and BaseFileManager::OnCreateFileMappingA().
Referenced by InstallClientHooks().
OnMapViewOfFile()
LPVOID WINAPI ClientRedirections::OnMapViewOfFile (__in HANDLE hFileMappingObject, __in DWORD dwDesiredAccess, __in DWORD dwFileOffsetHigh, __in DWORD dwFileOffsetLow, __in SIZE_T dwNumberOfBytesToMap) static private
This method is hooked into the client's MapViewOfFile function. It relays control to one of UltimaLive's concrete file managers.
Parameters
hFileMappingObject A handle to a file mapping object.
dwDesiredAccess The type of access to a file mapping object, which determines the protection of the pages.
dwFileOffsetHigh A high-order DWORD of the file offset where the view begins.
dwFileOffsetLow A low-order DWORD of the file offset where the view is to begin.
dwNumberOfBytesToMap The number of bytes of a file mapping to map to the view.
Returns
The starting address of the mapped view
Definition at line 288 of file ClientRedirections.cpp.
References UltimaLive::g_pUltimaLive, Client::GetFileManager(), UltimaLive::m_pClient, and BaseFileManager::OnMapViewOfFile().
Referenced by InstallClientHooks().
OnMessageBox()
int WINAPI ClientRedirections::OnMessageBox (_In_opt_ HWND hWnd, _In_opt_ LPCTSTR lpText, _In_opt_ LPCTSTR lpCaption, _In_ UINT uType) static private
This method is hooked into the client's MessageBox function.
Parameters
hWnd A handle to the owner window of the message box to be created.
lpText The message to be displayed.
lpCaption The dialog box title.
uType The contents and behavior of the dialog box.
Returns
If a message box has a Cancel button, the function returns the IDCANCEL value if either the ESC key is pressed or the Cancel button is selected. If the message box has no Cancel button, pressing ESC has no effect.
Definition at line 318 of file ClientRedirections.cpp.
References Logger::g_pLogger, and Logger::LogPrint().
Referenced by InstallClientHooks().
OnReceivePacket()
void __fastcall ClientRedirections::OnReceivePacket (void * This, void * edx, unsigned char * pBuffer) static private
This function is called in place of the client's network receive function. It passes control to the UltimaLive network manager which gives its subscribers the chance to alter/process each network packet before the client. It then calls the clients receive function.
Parameters
This Instance pointer
edx unknown
pBuffer Pointer to packet data
Definition at line 161 of file ClientRedirections.cpp.
References UltimaLive::g_pUltimaLive, Client::getRecvFunction(), and UltimaLive::m_pClient.
Referenced by InstallClientHooks().
OnSendPacket()
int __fastcall ClientRedirections::OnSendPacket (void * This, void * edx, unsigned char * pBuffer) static private
This function is called in place of the client's network send function. It passes control to the UltimaLive network manager which gives its subscribers the chance to alter/process each network packet before they are sent to the server. It then calls the clients receive function.
Parameters
This Pointer to class instance
edx unknown
pBuffer Pointer to packet data
Returns
0
Definition at line 181 of file ClientRedirections.cpp.
References UltimaLive::g_pUltimaLive, Client::getSendFunction(), and UltimaLive::m_pClient.
Referenced by InstallClientHooks().
The documentation for this class was generated from the following files:
UltimaLive/ClientRedirections.h
UltimaLive/ClientRedirections.cpp