UltimaLive: PacketHandlerFactory Class Reference
PacketHandlerFactory Class Reference
Abstract factory for packet handlers.
#include <PacketHandlerFactory.h>
Static Public Member Functions
static std::map< uint8_t, BasePacketHandler * > GenerateClientPacketHandlers (uint32_t versionMajor, uint32_t versionMinor, NetworkManager *pManager)
Factory method that generates client to server packet handlers.
static std::map< uint8_t, BasePacketHandler * > GenerateClientExtendedPacketHandlers (uint32_t versionMajor, uint32_t versionMinor, NetworkManager *pManager)
Factory method that generates client to server extended packet handlers.
static std::map< uint8_t, BasePacketHandler * > GenerateServerPacketHandlers (uint32_t versionMajor, uint32_t versionMinor, NetworkManager *pManager)
Factory method that generates server to client packet handlers.
static std::map< uint8_t, BasePacketHandler * > GenerateServerExtendedPacketHandlers (uint32_t versionMajor, uint32_t versionMinor, NetworkManager *pManager)
Factory method that generates server to client extended packet handlers.
static std::map< uint8_t, BasePacketHandler * > GenerateUltimaLiveServerPacketHandlers (uint32_t versionMajor, uint32_t versionMinor, NetworkManager *pManager)
Factory method that generates UltimaLive server to client packet handlers.
Detailed Description
Abstract factory for packet handlers.
Definition at line 38 of file PacketHandlerFactory.h.
Member Function Documentation
GenerateClientExtendedPacketHandlers()
std::map< uint8_t, BasePacketHandler * > PacketHandlerFactory::GenerateClientExtendedPacketHandlers (uint32_t versionMajor, uint32_t versionMinor, NetworkManager * pManager) static
Factory method that generates client to server extended packet handlers.
Parameters
versionMajor Client major version
versionMinor Client minor version
pManager Pointer to Network Manager Instance
Returns
Map of packet IDs to packet handlers
Definition at line 91 of file PacketHandlerFactory.cpp.
Referenced by NetworkManager::Initialize().
GenerateClientPacketHandlers()
std::map< uint8_t, BasePacketHandler * > PacketHandlerFactory::GenerateClientPacketHandlers (uint32_t versionMajor, uint32_t versionMinor, NetworkManager * pManager) static
Factory method that generates client to server packet handlers.
Parameters
pManager Pointer to Network Manager Instance
versionMajor Client Major Version
versionMinor Client Minor Version
Returns
Map of packet IDs to packet handlers
Definition at line 49 of file PacketHandlerFactory.cpp.
Referenced by NetworkManager::Initialize().
GenerateServerExtendedPacketHandlers()
std::map< uint8_t, BasePacketHandler * > PacketHandlerFactory::GenerateServerExtendedPacketHandlers (uint32_t versionMajor, uint32_t versionMinor, NetworkManager * pManager) static
Factory method that generates server to client extended packet handlers.
Parameters
versionMajor Client major version
versionMinor Client minor version
pManager Pointer to Network Manager Instance
Returns
Map of packet IDs to packet handlers
Definition at line 128 of file PacketHandlerFactory.cpp.
Referenced by NetworkManager::Initialize().
GenerateServerPacketHandlers()
std::map< uint8_t, BasePacketHandler * > PacketHandlerFactory::GenerateServerPacketHandlers (uint32_t versionMajor, uint32_t versionMinor, NetworkManager * pManager) static
Factory method that generates server to client packet handlers.
Parameters
versionMajor Client major version
versionMinor Client minor version
pManager Pointer to Network Manager Instance
Returns
Map of packet IDs to packet handlers
Definition at line 107 of file PacketHandlerFactory.cpp.
Referenced by NetworkManager::Initialize().
GenerateUltimaLiveServerPacketHandlers()
std::map< uint8_t, BasePacketHandler * > PacketHandlerFactory::GenerateUltimaLiveServerPacketHandlers (uint32_t versionMajor, uint32_t versionMinor, NetworkManager * pManager) static
Factory method that generates UltimaLive server to client packet handlers.
Parameters
versionMajor Client major version
versionMinor Client minor version
pManager Pointer to Network Manager Instance
Returns
Map of packet IDs to packet handlers
Definition at line 70 of file PacketHandlerFactory.cpp.
Referenced by NetworkManager::Initialize().
The documentation for this class was generated from the following files:
UltimaLive/Network/PacketHandlerFactory.h
UltimaLive/Network/PacketHandlerFactory.cpp