UltimaLive: UltimaLive Class Reference
UltimaLive Class Reference
Enables map streaming to the client and definition and use of additional maps.
#include <UltimaLive.h>
Public Member Functions
UltimaLive ()
UltimaLive class constructor.
void Start ()
Starts UltimaLive. Searches for internal client structures and prepares to start handling packets.
void Register (std::string name, void *obj)
Registers an instance of a class with a name.
void * Lookup (std::string name)
Looks up an instance of a class by name.
uint32_t GetVersionMajor ()
Returns the UltimaLive major version.
uint32_t GetVersionMinor ()
Returns the UltimaLive minor version.
Public Attributes
Client * m_pClient
Pointer to Client class instance.
Static Public Attributes
static UltimaLive * g_pUltimaLive = NULL
Global class instance of UltimaLive.
Private Attributes
uint32_t m_versionMajor
UltimaLive Major Version.
uint32_t m_versionMinor
UltimaLive Minor Version.
std::map< std::string, void * > m_registrations
Class instance registrations.
Detailed Description
Enables map streaming to the client and definition and use of additional maps.
Definition at line 45 of file UltimaLive.h.
Member Function Documentation
GetVersionMajor()
uint32_t UltimaLive::GetVersionMajor ()
Returns the UltimaLive major version.
Returns
Major version
Definition at line 163 of file UltimaLive.cpp.
References m_versionMajor.
Referenced by FileManagerFactory::Configure(), and NetworkManager::Initialize().
GetVersionMinor()
uint32_t UltimaLive::GetVersionMinor ()
Returns the UltimaLive minor version.
Returns
Minor version
Definition at line 173 of file UltimaLive.cpp.
References m_versionMinor.
Referenced by FileManagerFactory::Configure(), and NetworkManager::Initialize().
Lookup()
void * UltimaLive::Lookup (std::string name)
Looks up an instance of a class by name.
Parameters
name lookup string
Returns
Pointer to class instance
Definition at line 200 of file UltimaLive.cpp.
References m_registrations.
Referenced by FileManagerFactory::Initialize(), LoginHandler::Initialize(), Atlas::Initialize(), Client::Initialize(), and NetworkManager::Initialize().
Register()
void UltimaLive::Register (std::string name, void * obj)
Registers an instance of a class with a name.
Returns
Major version
Definition at line 183 of file UltimaLive.cpp.
References m_registrations.
Referenced by FileManagerFactory::Configure(), LoginHandler::Configure(), Atlas::Configure(), Client::Configure(), and NetworkManager::Configure().
The documentation for this class was generated from the following files:
UltimaLive/UltimaLive.h
UltimaLive/UltimaLive.cpp