UltimaLive: ProgressBarDialog Class Reference
ProgressBarDialog Class Reference
Displays a progress bar.
#include <ProgressBarDialog.h>
Public Member Functions
ProgressBarDialog ()
ProgressBarDialog constructor.
void show ()
Shows the Progress Bar Dialog.
void hide ()
Hides the progress Bar Dialog.
void setProgress (uint32_t progress)
Sets the progress bar percentage.
void setMessage (std::string message)
Set progress bar window title.
Static Public Member Functions
static BOOL CALLBACK DialogProc (HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam)
Dialog Process.
Private Attributes
HWND m_hDialog
Progress bar instance.
Detailed Description
Displays a progress bar.
Definition at line 39 of file ProgressBarDialog.h.
Member Function Documentation
DialogProc()
BOOL CALLBACK ProgressBarDialog::DialogProc (HWND hwnd, UINT message, WPARAM wParam, LPARAM lParam) static
Dialog Process.
Parameters
hwnd Window Handle
message Message to Display
wParam Unsigned Int pointer to windows param
lParam Long pointer to windows param
Returns
True on success
Definition at line 37 of file ProgressBarDialog.cpp.
Referenced by show().
setMessage()
void ProgressBarDialog::setMessage (std::string message)
Set progress bar window title.
Parameters
message Window title
Definition at line 92 of file ProgressBarDialog.cpp.
References m_hDialog.
Referenced by FileManager_7_0_29_2::InitializeShardMaps(), and BaseFileManager::InitializeShardMaps().
setProgress()
void ProgressBarDialog::setProgress (uint32_t progress)
Sets the progress bar percentage.
Parameters
progress Progress from 0 to 100
Definition at line 73 of file ProgressBarDialog.cpp.
References m_hDialog.
Referenced by UopUtility::convertUopMapToMul(), BaseFileManager::copyFile(), FileManager_7_0_29_2::InitializeShardMaps(), and BaseFileManager::InitializeShardMaps().
The documentation for this class was generated from the following files:
UltimaLive/ProgressBarDialog.h
UltimaLive/ProgressBarDialog.cpp