UltimaLive: UopUtility Class Reference
UopUtility Class Reference
Utilty Class for handling aspects of the UOP file format.
#include <UopUtility.h>
Static Public Member Functions
static uint64_t HashFileName (std::string s)
Calculates a hash based on the filename Information here obtained from UODEV.DE.
static std::map< uint32_t, uint64_t > * getMapHashes (int count, std::string pattern)
gets hashes corresponding to an internal map filename
static uint32_t getUopMapSizeInBytes (std::string filename)
Retrieves map size from UOP file. This method assumes that there is only one file table.
static void convertUopMapToMul (std::string uopSourceFilename, std::string uopDestFilename, ProgressBarDialog *pProgress)
Converts a UOP Map into a MUL File.
Detailed Description
Utilty Class for handling aspects of the UOP file format.
Definition at line 45 of file UopUtility.h.
Member Function Documentation
convertUopMapToMul()
void UopUtility::convertUopMapToMul (std::string uopSourceFilename, std::string uopDestFilename, ProgressBarDialog * pProgress) static
Converts a UOP Map into a MUL File.
Parameters
uopSourceFilename source file name
uopDestFilename destination file name
pProgress pointer to a progress bar
Definition at line 36 of file UopUtility.cpp.
References Logger::g_pLogger, Utils::getBaseFilenameWithoutExtension(), Utils::getFilenameFromPath(), getMapHashes(), Logger::LogPrint(), FileEntry::MetaDataSize, FileEntry::PathChecksum, ProgressBarDialog::setProgress(), FileEntry::UncompressedDataSize, FileEntry::unmarshal(), and FileEntry::UopFileOffset.
Referenced by FileManager_7_0_29_2::InitializeShardMaps().
getMapHashes()
std::map< uint32_t, uint64_t > * UopUtility::getMapHashes (int count, std::string pattern) static
gets hashes corresponding to an internal map filename
Parameters
count Number of maps
pattern filename and folder pattern
Returns
Map containing map number and hash for each map
Definition at line 201 of file UopUtility.cpp.
References HashFileName(), and ZeroPadNumber().
Referenced by convertUopMapToMul(), and FileManager_7_0_29_2::parseMapFile().
getUopMapSizeInBytes()
uint32_t UopUtility::getUopMapSizeInBytes (std::string filename) static
Retrieves map size from UOP file. This method assumes that there is only one file table.
Parameters
filename filename of the UOP file
Definition at line 127 of file UopUtility.cpp.
References FileEntry::CompressedDataSize, Logger::g_pLogger, Logger::LogPrint(), FileEntry::UncompressedDataSize, and FileEntry::unmarshal().
Referenced by FileManager_7_0_29_2::InitializeShardMaps().
HashFileName()
uint64_t UopUtility::HashFileName (std::string s) static
Calculates a hash based on the filename Information here obtained from UODEV.DE.
Returns
hash
Definition at line 229 of file UopUtility.cpp.
Referenced by getMapHashes().
The documentation for this class was generated from the following files:
UltimaLive/FileSystem/Uop/UopUtility.h
UltimaLive/FileSystem/Uop/UopUtility.cpp