UltimaLive: ServerVersionRequestHandler Class Reference
ServerVersionRequestHandler Class Reference
Handles the UltimaLive server request for version number.
#include <ServerVersionRequestHandler.h>
Public Member Functions
ServerVersionRequestHandler (NetworkManager *pManager)
ServerVersionRequestHandler constructor.
bool handlePacket (uint8_t *pPacketData)
Sends the UltimaLive version to the server.
Public Member Functions inherited from BasePacketHandler
BasePacketHandler (NetworkManager *pManager)
BasePacketHandler baseclass constructor.
Additional Inherited Members
Protected Attributes inherited from BasePacketHandler
NetworkManager * m_pManager
Pointer to the Network Manager Instance.
Detailed Description
Handles the UltimaLive server request for version number.
Definition at line 37 of file ServerVersionRequestHandler.h.
Member Function Documentation
handlePacket()
bool ServerVersionRequestHandler::handlePacket (uint8_t * pPacketData) virtual
Sends the UltimaLive version to the server.
Returns
True
Implements BasePacketHandler.
Definition at line 43 of file ServerVersionRequestHandler.cpp.
References Logger::g_pLogger, Utils::getModuleMinorVersionLower(), Utils::getModuleMinorVersionUpper(), Logger::LogPrint(), BasePacketHandler::m_pManager, and NetworkManager::sendPacketToServer().
The documentation for this class was generated from the following files:
UltimaLive/Network/ConcretePacketHandlers/ServerVersionRequestHandler.h
UltimaLive/Network/ConcretePacketHandlers/ServerVersionRequestHandler.cpp