UltimaLive: ChangeMapHandler Class Reference
ChangeMapHandler Class Reference
Decommutates Change Map Packets.
#include <ChangeMapHandler.h>
Public Member Functions
ChangeMapHandler (NetworkManager *pManager)
ChangeMapHandler constructor.
bool handlePacket (uint8_t *pPacketData)
Handles the map change packet from the server.
Public Member Functions inherited from BasePacketHandler
BasePacketHandler (NetworkManager *pManager)
BasePacketHandler baseclass constructor.
Additional Inherited Members
Protected Attributes inherited from BasePacketHandler
NetworkManager * m_pManager
Pointer to the Network Manager Instance.
Detailed Description
Decommutates Change Map Packets.
Definition at line 36 of file ChangeMapHandler.h.
Member Function Documentation
handlePacket()
bool ChangeMapHandler::handlePacket (uint8_t * pPacketData) virtual
Handles the map change packet from the server.
Packet Definition: byte 00 Packet ID: 0xBF (Extended Command) byte 01 - 02 Packet Size byte 03 - 04 Extended Command ID: 0x08 byte 05 Map ID
Parameters
pPacketData pointer to packet data
Returns
True on success
Implements BasePacketHandler.
Definition at line 50 of file ChangeMapHandler.cpp.
References Logger::g_pLogger, Logger::LogPrint(), BasePacketHandler::m_pManager, NetworkManager::onBeforeMapChange(), and NetworkManager::onMapChange().
The documentation for this class was generated from the following files:
UltimaLive/Network/ConcretePacketHandlers/ChangeMapHandler.h
UltimaLive/Network/ConcretePacketHandlers/ChangeMapHandler.cpp