UltimaLive: BaseSelfRegisteringClass Class Reference
BaseSelfRegisteringClass Class Reference
Base class that enables classes to self register (typically as factories)
#include <BaseSelfRegisteringClass.h>
Public Member Functions
virtual ~BaseSelfRegisteringClass ()
Constructor for BaseSelfRegistering class.
Static Public Member Functions
static void Configure ()
Calls all static stored class configuration functions.
static bool Initialize ()
Calls all static stored class initialization functions.
Protected Member Functions
BaseSelfRegisteringClass (void(*)(), bool(*)())
Overloaded constructor for BaseSelfRegistering class. Stores function pointers for later retrieval.
Static Private Member Functions
static std::vector< bool(*)(void)> & getInitalizationFunctions ()
static std::vector< void(*)(void)> & getConfigurationFunctions ()
Uses the Construct On First Use Idiom to get the list of configuration functions.
Detailed Description
Base class that enables classes to self register (typically as factories)
Definition at line 38 of file BaseSelfRegisteringClass.h.
Constructor & Destructor Documentation
BaseSelfRegisteringClass()
BaseSelfRegisteringClass::BaseSelfRegisteringClass (void(*)() config, bool(*)() init) protected
Overloaded constructor for BaseSelfRegistering class. Stores function pointers for later retrieval.
Function pointers are passed in by the SelfRegisteringClass automatically through templating
Parameters
config Function pointer to each class's static configure function
init Function pointer to each class's static initialization function
Definition at line 43 of file BaseSelfRegisteringClass.cpp.
References getConfigurationFunctions(), and getInitalizationFunctions().
Member Function Documentation
getConfigurationFunctions()
std::vector< void(*)(void)> & BaseSelfRegisteringClass::getConfigurationFunctions () static private
Uses the Construct On First Use Idiom to get the list of configuration functions.
Returns
vector of function pointers to configuration functions
Definition at line 103 of file BaseSelfRegisteringClass.cpp.
Referenced by BaseSelfRegisteringClass(), and Configure().
getInitalizationFunctions()
std::vector< bool(*)(void)> & BaseSelfRegisteringClass::getInitalizationFunctions () static private
Uses the Construct On First Use Idiom to get the list of initialization functions.
These static variables must be wrapped in functions See: http://stackoverflow.com/questions/1005685/c-static-initialization-order and see:http://www.parashift.com/c++-faq-lite/ctors.html::faq-10.12
There is a danger to this method if not used propertly: see: http://www.parashift.com/c++-faq/construct-on-first-use-v2.html
return vector of function pointers to initialization functions
Definition at line 92 of file BaseSelfRegisteringClass.cpp.
Referenced by BaseSelfRegisteringClass(), and Initialize().
The documentation for this class was generated from the following files:
UltimaLive/ClassRegistration/BaseSelfRegisteringClass.h
UltimaLive/ClassRegistration/BaseSelfRegisteringClass.cpp