UltimaLive: NetworkManager Class Reference
NetworkManager Class Reference
Handles network packets going to/from the server/client.
#include <NetworkManager.h>
Public Member Functions
NetworkManager ()
NetworkManager constructor.
bool OnReceivePacket (unsigned char *pBuffer)
Called to handle server packets. Calls packet handlers in turn.
bool OnSendPacket (unsigned char *pBuffer)
Calls packet handlers on an outgoing packet.
void sendPacketToClient (uint8_t *pBuffer)
Sends a packet to the client using the client class.
void sendPacketToServer (uint8_t *pBuffer)
Sends a packet to the server using the client class.
void onMapDefinitionUpdate (std::vector< MapDefinition > definitions)
Fires the update map definitions event.
void onLandUpdate (uint8_t mapNumber, uint32_t blockNumber, uint8_t *pLandData)
Fires the update land event.
void onStaticsUpdate (uint8_t mapNumber, uint32_t blockNumber, uint8_t *pStaticsData, uint32_t length)
Fires the update statics event.
void onRefreshClient ()
Fires the refresh client event.
void onBlockQueryRequest (int32_t blockNumber, uint8_t mapNumber)
Fires the block query request event.
void onUltimaLiveLoginComplete (std::string shardIdentifier)
Fires the Ultaima Live Login Complete event.
void onServerMobileUpdate ()
Fires the Server Mobile Update event.
void onLoginConfirm (uint8_t *pData)
Fires the Login Confirm event.
void onLoginComplete ()
Fires the Login Complete event.
void onBeforeMapChange (uint8_t &mapNumber)
Fires the Before Map Change event.
void onMapChange (uint8_t &mapNumber)
Fires the Map Change event.
void onLogout ()
Fires the Log Out event.
void subscribeToMapDefinitionUpdate (std::function< void(std::vector< MapDefinition >)> pCallback)
Subscribes to the UltimaLive update map definitions packet.
void subscribeToLandUpdate (std::function< void(uint8_t, uint32_t, uint8_t *)> pCallback)
Subscribes to the UltimaLive update land packet.
void subscribeToStaticsUpdate (std::function< void(uint8_t, uint32_t, uint8_t *, uint32_t)> pCallback)
Subscribes to the UltimaLive update statics packet.
void subscribeToRefreshClient (std::function< void()> pCallback)
Subscribes to the UltimaLive refresh client packet.
void subscribeToBlockQueryRequest (std::function< void(int32_t, uint8_t)> pCallback)
Subscribes to the UltimaLive block query packet.
void subscribeToUltimaLiveLoginComplete (std::function< void(std::string)> pCallback)
Subscribes to the UltimaLive login complete packet.
void subscribeToServerMobileUpdate (std::function< void()> pCallback)
Subscribes to the Update Mobile packet.
void subscribeToLoginConfirm (std::function< void(uint8_t *)> pCallback)
Subscribes to the Login Confirm packet.
void subscribeToLoginComplete (std::function< void()> pCallback)
Subscribes to the Login Complete packet.
void subscribeToOnBeforeMapChange (std::function< void(uint8_t &)> pCallback)
Subscribes to on before Map Change packet event.
void subscribeToOnMapChange (std::function< void(uint8_t &)> pCallback)
Subscribes to the Map Change packet.
void subscribeToLogout (std::function< void()> pCallback)
Subscribes to the Logout packet.
Static Public Member Functions
static bool Initialize ()
Called by self registering class construct. Generate packets handlers using Packet Handler Factories.
static void Configure ()
Creates global instance of network manager and register it with UltimaLive.
Private Member Functions
bool OnReceiveServerUltimaLivePacket (unsigned char *pBuffer)
Called to handle UltimaLive packets. Calls packet handlers in turn.
bool OnReceiveExtendedPacket (unsigned char *pBuffer)
Handles extended packets from the server.
bool OnSendExtendedPacket (unsigned char *pBuffer)
Handles extended packets before they are sent to the server.
Private Attributes
std::vector< std::function< void(std::vector< MapDefinition >)> > m_onMapDefinitionUpdateSubscribers
MapDefinitionUpdate event subscriber list.
std::vector< std::function< void(uint8_t, uint32_t, uint8_t *)> > m_onLandUpdateSubscriber
LandUpdate event subscriber list.
std::vector< std::function< void(uint8_t, uint32_t, uint8_t *, uint32_t)> > m_onStaticsUpdateSubscriber
StaticsUpdate event subscriber list.
std::vector< std::function< void()> > m_onRefreshClientViewSubscriber
RefreshClientView event subscriber list.
std::vector< std::function< void(uint32_t, uint8_t)> > m_onBlockQueryRequestSubscriber
BlockQueryRequest event subscriber list.
std::vector< std::function< void(std::string)> > m_onUltimaLiveLoginCompleteSubscriber
UltimaLive LoginComplete event subscriber list.
std::vector< std::function< void()> > m_onServerMobileUpdateSubscribers
MobileUpdate event subscriber list.
std::vector< std::function< void(uint8_t *)> > m_onLoginConfirmSubscribers
LoginConfirm event subscriber list.
std::vector< std::function< void()> > m_onLoginCompleteSubscribers
LoginComplete event subscriber list.
std::vector< std::function< void(uint8_t &)> > m_onBeforeMapChangeSubscribers
BeforeMapChange event subscriber list.
std::vector< std::function< void(uint8_t &)> > m_onChangeMapSubscribers
ChangeMap event subscriber list.
std::vector< std::function< void()> > m_onLogoutSubscribers
Logout event subscriber list.
std::map< uint8_t, BasePacketHandler * > m_ultimaLiveHandlers
UltimaLive Packet Handlers.
std::map< uint8_t, BasePacketHandler * > m_sendPacketHandlers
Client to Server Packet Handlers.
std::map< uint8_t, BasePacketHandler * > m_recvPacketHandlers
Server to Client Packet Handlers.
std::map< uint8_t, BasePacketHandler * > m_sendExtendedPacketHandlers
Client to Server Extended Packet Handlers.
std::map< uint8_t, BasePacketHandler * > m_recvExtendedPacketHandlers
Server to Client Extended Packet Handlers.
Client * m_pClient
Local reference to the global client class instance.
Static Private Attributes
static SelfRegisteringClass< NetworkManager > m_registration
Self Registering Class mechanism.
Detailed Description
Handles network packets going to/from the server/client.
Definition at line 73 of file NetworkManager.h.
Member Function Documentation
Initialize()
bool NetworkManager::Initialize () static
Called by self registering class construct. Generate packets handlers using Packet Handler Factories.
Returns
True on success
Definition at line 46 of file NetworkManager.cpp.
References Logger::g_pLogger, UltimaLive::g_pUltimaLive, PacketHandlerFactory::GenerateClientExtendedPacketHandlers(), PacketHandlerFactory::GenerateClientPacketHandlers(), PacketHandlerFactory::GenerateServerExtendedPacketHandlers(), PacketHandlerFactory::GenerateServerPacketHandlers(), PacketHandlerFactory::GenerateUltimaLiveServerPacketHandlers(), UltimaLive::GetVersionMajor(), UltimaLive::GetVersionMinor(), Logger::LogPrint(), Logger::LogPrintError(), Logger::LogPrintTaskStatusResult(), Logger::LogPrintWithoutDate(), UltimaLive::Lookup(), m_pClient, m_recvExtendedPacketHandlers, m_recvPacketHandlers, m_sendExtendedPacketHandlers, m_sendPacketHandlers, and m_ultimaLiveHandlers.
onBeforeMapChange()
void NetworkManager::onBeforeMapChange (uint8_t & mapNumber)
Fires the Before Map Change event.
Parameters
mapNumber Map Number
Definition at line 567 of file NetworkManager.cpp.
References m_onBeforeMapChangeSubscribers.
Referenced by ChangeMapHandler::handlePacket(), and ChangeMapHandler_7_0_29_2::handlePacket().
onBlockQueryRequest()
void NetworkManager::onBlockQueryRequest (int32_t blockNumber, uint8_t mapNumber)
Fires the block query request event.
Parameters
blockNumber Block Number
mapNumber Map Number
Definition at line 506 of file NetworkManager.cpp.
References m_onBlockQueryRequestSubscriber.
Referenced by UltimaLiveHashQueryHandler::handlePacket().
onLandUpdate()
void NetworkManager::onLandUpdate (uint8_t mapNumber, uint32_t blockNumber, uint8_t * pLandData)
Fires the update land event.
Parameters
mapNumber Map Number
blockNumber Block Number
pLandData pointer to land data
Definition at line 465 of file NetworkManager.cpp.
References m_onLandUpdateSubscriber.
Referenced by UltimaLiveUpdateLandBlockHandler::handlePacket().
onLoginConfirm()
void NetworkManager::onLoginConfirm (uint8_t * pData)
Fires the Login Confirm event.
Parameters
pData Pointer packet data
Definition at line 543 of file NetworkManager.cpp.
References m_onLoginConfirmSubscribers.
Referenced by LoginConfirmHandler::handlePacket(), and LoginConfirmHandler_7_0_29_2::handlePacket().
onMapChange()
void NetworkManager::onMapChange (uint8_t & mapNumber)
Fires the Map Change event.
Parameters
mapNumber Map Number
Definition at line 580 of file NetworkManager.cpp.
References m_onChangeMapSubscribers.
Referenced by ChangeMapHandler::handlePacket(), and ChangeMapHandler_7_0_29_2::handlePacket().
onMapDefinitionUpdate()
void NetworkManager::onMapDefinitionUpdate (std::vector< MapDefinition > definitions)
Fires the update map definitions event.
Parameters
definitions Map Definitions
Definition at line 450 of file NetworkManager.cpp.
References m_onMapDefinitionUpdateSubscribers.
Referenced by UltimaLiveUpdateMapDefinitionsHandler::handlePacket().
OnReceiveExtendedPacket()
bool NetworkManager::OnReceiveExtendedPacket (unsigned char * pBuffer) private
Handles extended packets from the server.
Parameters
pBuffer Pointer to packet data
Returns
True to pass packet onto server
Definition at line 277 of file NetworkManager.cpp.
References Logger::g_pLogger, Logger::LogPacketToClient(), and m_recvExtendedPacketHandlers.
Referenced by OnReceivePacket().
OnReceivePacket()
bool NetworkManager::OnReceivePacket (unsigned char * pBuffer)
Called to handle server packets. Calls packet handlers in turn.
Parameters
pBuffer Pointer to packet data
Returns
Returns the return code from the called packet handler. If false, do not forward packets to client.
Definition at line 184 of file NetworkManager.cpp.
References Logger::g_pLogger, Logger::LogPacketToClient(), m_recvPacketHandlers, OnReceiveExtendedPacket(), and OnReceiveServerUltimaLivePacket().
OnReceiveServerUltimaLivePacket()
bool NetworkManager::OnReceiveServerUltimaLivePacket (unsigned char * pBuffer) private
Called to handle UltimaLive packets. Calls packet handlers in turn.
Returns
False (does not forward packets to client)
Definition at line 157 of file NetworkManager.cpp.
References Logger::g_pLogger, Logger::LogPacketToClient(), and m_ultimaLiveHandlers.
Referenced by OnReceivePacket().
OnSendExtendedPacket()
bool NetworkManager::OnSendExtendedPacket (unsigned char * pBuffer) private
Handles extended packets before they are sent to the server.
Parameters
pBuffer Pointer to data packet
Returns
True to pass data onto server
Definition at line 305 of file NetworkManager.cpp.
References Logger::g_pLogger, Logger::LogPacketToServer(), and m_sendExtendedPacketHandlers.
Referenced by OnSendPacket().
OnSendPacket()
bool NetworkManager::OnSendPacket (unsigned char * pBuffer)
Calls packet handlers on an outgoing packet.
Parameters
pBuffer Pointer to packet data
Returns
true to forward the packet onto the server
Definition at line 238 of file NetworkManager.cpp.
References Logger::g_pLogger, Logger::LogPacketToServer(), Logger::LogPrint(), m_sendPacketHandlers, and OnSendExtendedPacket().
onStaticsUpdate()
void NetworkManager::onStaticsUpdate (uint8_t mapNumber, uint32_t blockNumber, uint8_t * pStaticsData, uint32_t length)
Fires the update statics event.
Parameters
mapNumber Map Number
blockNumber Block Number
pStaticsData Pointer to statics data
length of statics data in bytes
Definition at line 481 of file NetworkManager.cpp.
References m_onStaticsUpdateSubscriber.
Referenced by UltimaLiveUpdateStaticsHandler::handlePacket().
onUltimaLiveLoginComplete()
void NetworkManager::onUltimaLiveLoginComplete (std::string shardIdentifier)
Fires the Ultaima Live Login Complete event.
Parameters
shardIdentifier Unique Shard Identifier
Definition at line 519 of file NetworkManager.cpp.
References m_onUltimaLiveLoginCompleteSubscriber.
Referenced by UltimaLiveLoginCompleteHandler::handlePacket().
sendPacketToClient()
void NetworkManager::sendPacketToClient (uint8_t * pBuffer)
Sends a packet to the client using the client class.
Parameters
pBuffer Pointer to packet data
Definition at line 111 of file NetworkManager.cpp.
References m_pClient, and Client::SendPacketToClient().
Referenced by LoginHandler::onBeforeMapChange(), Atlas::onBeforeMapChange(), LoginHandler::onLoginComplete(), and Atlas::onRefreshClientView().
sendPacketToServer()
void NetworkManager::sendPacketToServer (uint8_t * pBuffer)
Sends a packet to the server using the client class.
Parameters
pBuffer Pointer to packet data
Definition at line 121 of file NetworkManager.cpp.
References m_pClient, and Client::SendPacketToServer().
Referenced by ServerVersionRequestHandler::handlePacket(), and Atlas::onHashQuery().
subscribeToBlockQueryRequest()
void NetworkManager::subscribeToBlockQueryRequest (std::function< void(int32_t, uint8_t)> pCallback)
Subscribes to the UltimaLive block query packet.
Parameters
pCallback Packet handler function
Definition at line 370 of file NetworkManager.cpp.
References m_onBlockQueryRequestSubscriber.
Referenced by Atlas::Initialize().
subscribeToLandUpdate()
void NetworkManager::subscribeToLandUpdate (std::function< void(uint8_t, uint32_t, uint8_t *)> pCallback)
Subscribes to the UltimaLive update land packet.
Parameters
pCallback Packet handler function
Definition at line 340 of file NetworkManager.cpp.
References m_onLandUpdateSubscriber.
Referenced by Atlas::Initialize().
subscribeToLoginComplete()
void NetworkManager::subscribeToLoginComplete (std::function< void()> pCallback)
Subscribes to the Login Complete packet.
Parameters
pCallback Packet handler function
Definition at line 410 of file NetworkManager.cpp.
References m_onLoginCompleteSubscribers.
Referenced by LoginHandler::Initialize().
subscribeToLoginConfirm()
void NetworkManager::subscribeToLoginConfirm (std::function< void(uint8_t *)> pCallback)
Subscribes to the Login Confirm packet.
Parameters
pCallback Packet handler function
Definition at line 400 of file NetworkManager.cpp.
References m_onLoginConfirmSubscribers.
Referenced by LoginHandler::Initialize().
subscribeToLogout()
void NetworkManager::subscribeToLogout (std::function< void()> pCallback)
Subscribes to the Logout packet.
Parameters
pCallback Packet handler function
Definition at line 440 of file NetworkManager.cpp.
References m_onLogoutSubscribers.
Referenced by LoginHandler::Initialize(), and Atlas::Initialize().
subscribeToMapDefinitionUpdate()
void NetworkManager::subscribeToMapDefinitionUpdate (std::function< void(std::vector< MapDefinition >)> pCallback)
Subscribes to the UltimaLive update map definitions packet.
Parameters
pCallback Packet handler function
Definition at line 330 of file NetworkManager.cpp.
References m_onMapDefinitionUpdateSubscribers.
Referenced by LoginHandler::Initialize(), and Atlas::Initialize().
subscribeToOnBeforeMapChange()
void NetworkManager::subscribeToOnBeforeMapChange (std::function< void(uint8_t &)> pCallback)
Subscribes to on before Map Change packet event.
Parameters
pCallback Packet handler function
Definition at line 420 of file NetworkManager.cpp.
References m_onBeforeMapChangeSubscribers.
Referenced by LoginHandler::Initialize(), and Atlas::Initialize().
subscribeToOnMapChange()
void NetworkManager::subscribeToOnMapChange (std::function< void(uint8_t &)> pCallback)
Subscribes to the Map Change packet.
Parameters
pCallback Packet handler function
Definition at line 430 of file NetworkManager.cpp.
References m_onChangeMapSubscribers.
Referenced by Atlas::Initialize().
subscribeToRefreshClient()
void NetworkManager::subscribeToRefreshClient (std::function< void()> pCallback)
Subscribes to the UltimaLive refresh client packet.
Parameters
pCallback Packet handler function
Definition at line 360 of file NetworkManager.cpp.
References m_onRefreshClientViewSubscriber.
Referenced by Atlas::Initialize().
subscribeToServerMobileUpdate()
void NetworkManager::subscribeToServerMobileUpdate (std::function< void()> pCallback)
Subscribes to the Update Mobile packet.
Parameters
pCallback Packet handler function
Definition at line 390 of file NetworkManager.cpp.
References m_onServerMobileUpdateSubscribers.
Referenced by LoginHandler::Initialize().
subscribeToStaticsUpdate()
void NetworkManager::subscribeToStaticsUpdate (std::function< void(uint8_t, uint32_t, uint8_t *, uint32_t)> pCallback)
Subscribes to the UltimaLive update statics packet.
Parameters
pCallback Packet handler function
Definition at line 350 of file NetworkManager.cpp.
References m_onStaticsUpdateSubscriber.
Referenced by Atlas::Initialize().
subscribeToUltimaLiveLoginComplete()
void NetworkManager::subscribeToUltimaLiveLoginComplete (std::function< void(std::string)> pCallback)
Subscribes to the UltimaLive login complete packet.
Parameters
pCallback Packet handler function
Definition at line 380 of file NetworkManager.cpp.
References m_onUltimaLiveLoginCompleteSubscriber.
Referenced by Atlas::Initialize().
The documentation for this class was generated from the following files:
UltimaLive/Network/NetworkManager.h
UltimaLive/Network/NetworkManager.cpp