UltimaLive: FileManager Class Reference
FileManager Class Reference
FileManager class for clients using MUL files.
#include <FileManager.h>
Public Member Functions
FileManager ()
FileManager constructor.
LPVOID WINAPI OnMapViewOfFile (__in HANDLE hFileMappingObject, __in DWORD dwDesiredAccess, __in DWORD dwFileOffsetHigh, __in DWORD dwFileOffsetLow, __in SIZE_T dwNumberOfBytesToMap)
Creates the shared memory spaces for map files, static files and indices This method is called in place of the client's original MapViewOfFile. Instead of mapping a view of each file that the client needs, a single shared space is mapped so that UltimaLive can dynamically load and unload maps as needed.
bool Initialize ()
Initialization function for the FileManager.
void LoadMap (uint8_t mapNumber)
Loads a map specified by number into the shared memory space in the client.
Public Member Functions inherited from BaseFileManager
BaseFileManager ()
BaseFileManager constructor.
virtual HANDLE WINAPI OnCreateFileA (__in LPCSTR lpFileName, __in DWORD dwDesiredAccess, __in DWORD dwShareMode, __in_opt LPSECURITY_ATTRIBUTES lpSecurityAttributes, __in DWORD dwCreationDisposition, __in DWORD dwFlagsAndAttributes, __in_opt HANDLE hTemplateFile)
Called when the client calls CreateFileA. Caches object handles needed by filemanagers.
virtual HANDLE WINAPI OnCreateFileMappingA (__in HANDLE hFile, __in_opt LPSECURITY_ATTRIBUTES lpAttributes, __in DWORD flProtect, __in DWORD dwMaximumSizeHigh, __in DWORD dwMaximumSizeLow, __in_opt LPCSTR lpName)
Called when the client calls createfilemapping. Stores a file mapping with a matching fileset if its a file UltimaLive Tracks.
virtual BOOL WINAPI OnCloseHandle (_In_ HANDLE hObject)
Called when the client calls its CloseHandle function. Removes filenames from the list of open handles.
virtual unsigned char * readStaticsBlock (uint32_t mapNumber, uint32_t blockNum, uint32_t &rNumberOfBytesOut)
reads data corresponding to all statics contained in one map block
virtual bool writeStaticsBlock (uint8_t mapNumber, uint32_t blockNum, uint8_t *pBlockData, uint32_t length)
Writes data corresponding to the statics in a map block out to memory and to the UltimaLive file cache.
virtual void InitializeShardMaps (std::string shardIdentifier, std::map< uint32_t, MapDefinition > definitions)
Initializes a shards maps by creating or copying new maps into the UltimaLive file cache.
virtual void onLogout ()
handles client logout and prepares UltimaLive for a new login
virtual bool updateLandBlock (uint8_t mapNumber, uint32_t blockNum, uint8_t *pData)
updates a land block in memory and in UltimaLive's map cache on disk
virtual unsigned char * readLandBlock (uint8_t mapNumber, uint32_t blockNum)
Reads a land block and returns a pointer to the newly allocated memory. Caller is responsible for memory cleanup.
Protected Member Functions
unsigned char * seekLandBlock (uint8_t mapNumber, uint32_t blockNum)
Finds a memory location corresponding to a block number.
Protected Member Functions inherited from BaseFileManager
std::string getUltimaLiveSavePath ()
Gets the UltimaLive cache path for the platform.
virtual bool createNewPersistentMap (std::string pathWithoutFilename, uint8_t mapNumber, uint32_t numHorizontalBlocks, uint32_t numVerticalBlocks)
Creates a new blank map in the map store from scratch.
bool checkValidMemoryAllocated (void *pBuffer)
Checks to see if UltimaLive has allocated a valid pool of memory.
Protected Attributes
std::map< std::string, uint32_t > m_neededFiles
Files that this file manager will handle.
Protected Attributes inherited from BaseFileManager
std::map< std::string, ClientFileHandleSet * > m_files
Maps the base map name to the set of handles for the corresponding files (map#.mul, staidx#.mul statics#.mul)
uint8_t * m_pMapPool
Pointer to the memory pool used to load and unload maps.
uint8_t * m_pStaticsPool
Pointer to the memory pool used to load and unload statics.
uint8_t * m_pStaticsPoolEnd
Pointer to the end of the statics memory pool.
uint8_t * m_pStaidxPool
Pointer to the statics index memory pool.
uint8_t * m_pStaidxPoolEnd
Pointer to the end of the statics index memory pool.
std::string m_shardIdentifier
Unique shard identifier.
std::ofstream * m_pMapFileStream
Pointer to map file stream.
std::ofstream * m_pStaidxFileStream
Pointer to statics index file stream.
std::ofstream * m_pStaticsFileStream
Pointer to statics file stream.
ProgressBarDialog * m_pProgressDlg
Pointer to the progress bar dialog.
Additional Inherited Members
Static Public Member Functions inherited from BaseFileManager
static void copyFile (std::string sourceFilePath, std::string destFilePath, ProgressBarDialog *pProgress)
Copy a file from one location to another.
Static Public Attributes inherited from BaseFileManager
static const int MAP_MEMORY_SIZE = 100000000
Memory to allocate for the largest possible map file.
static const int STAIDX_MEMORY_SIZE = 10000000
Memory to allocate for the largest possible statics index file.
static const int STATICS_MEMORY_SIZE = 200000000
Memory to allocate for the largets possible statics file.
Detailed Description
FileManager class for clients using MUL files.
Definition at line 46 of file FileManager.h.
Member Function Documentation
Initialize()
bool FileManager::Initialize () virtual
Initialization function for the FileManager.
Returns
True on success
Reimplemented from BaseFileManager.
Definition at line 250 of file FileManager.cpp.
References Logger::g_pLogger, BaseFileManager::Initialize(), and Logger::LogPrint().
LoadMap()
void FileManager::LoadMap (uint8_t mapNumber) virtual
Loads a map specified by number into the shared memory space in the client.
Parameters
mapNumber Number corresponding to the map that the client should load (map0.mul, etc)
Implements BaseFileManager.
Definition at line 68 of file FileManager.cpp.
References Logger::g_pLogger, BaseFileManager::getUltimaLiveSavePath(), Logger::LogPrint(), BaseFileManager::m_pMapFileStream, BaseFileManager::m_pMapPool, BaseFileManager::m_pStaidxFileStream, BaseFileManager::m_pStaidxPool, BaseFileManager::m_pStaticsFileStream, BaseFileManager::m_pStaticsPool, BaseFileManager::m_pStaticsPoolEnd, and BaseFileManager::m_shardIdentifier.
OnMapViewOfFile()
LPVOID WINAPI FileManager::OnMapViewOfFile (__in HANDLE hFileMappingObject, __in DWORD dwDesiredAccess, __in DWORD dwFileOffsetHigh, __in DWORD dwFileOffsetLow, __in SIZE_T dwNumberOfBytesToMap) virtual
Creates the shared memory spaces for map files, static files and indices This method is called in place of the client's original MapViewOfFile. Instead of mapping a view of each file that the client needs, a single shared space is mapped so that UltimaLive can dynamically load and unload maps as needed.
Parameters
hFileMappingObject A handle to a file mapping object.
dwDesiredAccess The type of access to a file mapping object, which determines the protection of the pages.
dwFileOffsetHigh A high-order DWORD of the file offset where the view begins.
dwFileOffsetLow A low-order DWORD of the file offset where the view is to begin.
dwNumberOfBytesToMap The number of bytes of a file mapping to map to the view.
Returns
The starting address of the mapped view
Reimplemented from BaseFileManager.
Definition at line 176 of file FileManager.cpp.
References Utils::getFilenameFromPath(), ClientFileHandleSet::m_filename, BaseFileManager::m_files, ClientFileHandleSet::m_mapFileViewHandle, m_neededFiles, BaseFileManager::m_pMapPool, BaseFileManager::m_pStaidxPool, and BaseFileManager::m_pStaticsPool.
seekLandBlock()
unsigned char * FileManager::seekLandBlock (uint8_t mapNumber, uint32_t blockNum) protected virtual
Finds a memory location corresponding to a block number.
Parameters
mapNumber Map Number
blockNum Block Number to seek
Returns
pointer to the block data
Implements BaseFileManager.
Definition at line 239 of file FileManager.cpp.
References BaseFileManager::m_pMapPool.
The documentation for this class was generated from the following files:
UltimaLive/FileSystem/ConcreteFileManagers/FileManager.h
UltimaLive/FileSystem/ConcreteFileManagers/FileManager.cpp