UltimaLive: Utils Class Reference
Utils Class Reference
Utility class for UltimaLive.
#include <Utils.h>
Static Public Member Functions
static std::string GetCurrentModuleName ()
Gets the name of the current module.
static std::string GetCurrentModuleFullPath ()
Gets the path to the current process including the filename.
static std::string GetCurrentPathWithoutFilename ()
Gets the path to the current process without the filename.
static bool IsElevated ()
Check to see if the current process has admin rights verbose Taken from http://stackoverflow.com/questions/8046097/how-to-check-if-a-process-has-the-admin-rights.
static std::string getFilenameFromPath (std::string path)
Returns a filename with the extension from a path string.
static std::string getBaseFilenameWithoutExtension (std::string filename)
Gets the base filename without the extension from a given path.
static int getModuleMinorVersionLower ()
Getter for UltimaLive major version.
static int getModuleMinorVersionUpper ()
Getter for UltimaLive minor version.
static std::wstring s2ws (const std::string &s)
converts standard string to wstring
Static Public Attributes
static const int MAX_PATH_LENGTH = 2048
Length Constant.
Detailed Description
Utility class for UltimaLive.
Definition at line 50 of file Utils.h.
Member Function Documentation
getBaseFilenameWithoutExtension()
std::string Utils::getBaseFilenameWithoutExtension (std::string filename) static
Gets the base filename without the extension from a given path.
Parameters
filename File path
Returns
basefilename without the extension
Definition at line 196 of file Utils.cpp.
Referenced by UopUtility::convertUopMapToMul().
GetCurrentModuleFullPath()
std::string Utils::GetCurrentModuleFullPath () static
Gets the path to the current process including the filename.
Returns
Path to the current process including process name
Definition at line 88 of file Utils.cpp.
References Logger::g_pLogger, and Logger::LogPrint().
Referenced by UltimaLive::UltimaLive().
GetCurrentModuleName()
std::string Utils::GetCurrentModuleName () static
Gets the name of the current module.
Returns
Name of current module
Definition at line 53 of file Utils.cpp.
Referenced by ClientRedirections::InstallClientHooks(), and UltimaLive::Start().
GetCurrentPathWithoutFilename()
std::string Utils::GetCurrentPathWithoutFilename () static
Gets the path to the current process without the filename.
Returns
Path to the current process
Definition at line 75 of file Utils.cpp.
Referenced by FileManager_7_0_29_2::InitializeShardMaps(), and BaseFileManager::InitializeShardMaps().
getFilenameFromPath()
std::string Utils::getFilenameFromPath (std::string path) static
Returns a filename with the extension from a path string.
Parameters
path Path with filename
Returns
Filename with extention
Definition at line 226 of file Utils.cpp.
Referenced by UopUtility::convertUopMapToMul(), BaseFileManager::OnCreateFileA(), FileManager::OnMapViewOfFile(), and FileManager_7_0_29_2::OnMapViewOfFile().
getModuleMinorVersionLower()
int Utils::getModuleMinorVersionLower () static
Getter for UltimaLive major version.
Returns
Major Version
Definition at line 130 of file Utils.cpp.
References getModuleMinorVersionUpper().
Referenced by ServerVersionRequestHandler::handlePacket(), and LoginHandler::onLoginComplete().
getModuleMinorVersionUpper()
int Utils::getModuleMinorVersionUpper () static
Getter for UltimaLive minor version.
Returns
Minor Version
Definition at line 147 of file Utils.cpp.
Referenced by getModuleMinorVersionLower(), ServerVersionRequestHandler::handlePacket(), and LoginHandler::onLoginComplete().
IsElevated()
bool Utils::IsElevated () static
Check to see if the current process has admin rights verbose Taken from http://stackoverflow.com/questions/8046097/how-to-check-if-a-process-has-the-admin-rights.
Returns
True if process has admin rights
Definition at line 167 of file Utils.cpp.
s2ws()
std::wstring Utils::s2ws (const std::string & s) static
converts standard string to wstring
Parameters
s string to convert
Returns
converted wstring
Definition at line 36 of file Utils.cpp.
Referenced by DotNetHost::LaunchNetAssembly().
The documentation for this class was generated from the following files:
UltimaLive/Utils.h
UltimaLive/Utils.cpp