UltimaLive: Client Class Reference
Client Class Reference
This class knows about the client internals. This class assumes that it shares memory space with the actual client, therefor no calls to get memory from an external process are used.
#include <Client.h>
Public Types
typedef void(__thiscall * ClientRecvFunction) (void *This, unsigned char *pBuffer)
Client Receive Function type.
typedef int(__thiscall * ClientSendFunction) (void *This, unsigned char *pBuffer)
Client Send Function type.
typedef void(__cdecl * ClientUpdateStaticBlocksFunction) ()
Client Update Statics Block function type.
typedef int(__cdecl * RefreshTerrainFunction) ()
Refresh Terrain Function type.
Public Member Functions
Client ()
Client class constructor.
void SendPacketToServer (unsigned char *pBuffer)
Sends an array of bytes to the server using the clients send function.
void SendPacketToClient (unsigned char *pBuffer)
Sends an array of bytes to the client using the clients receive function.
void refreshClientLand ()
Refreshes the land tiles on the client screen.
void refreshClientStatics (uint32_t blockNumber)
Refreshes statics on the client screen for a given block.
void SetMapDimensions (MapTileDefinition definition)
Updates the client's map dimensions.
CPlayerMobile * getPlayerMobile ()
Getter for the pointer to the client Player structure.
bool LookupClientInternalStructuresAndFunctions ()
Search out all internal structure addresses.
ClientRecvFunction & getRecvFunction ()
Getter for client's Receive Function pointer.
ClientSendFunction & getSendFunction ()
Getter for client's Send Function pointer.
ClientUpdateStaticBlocksFunction & getUpdatesStaticBlocksFunction ()
Getter for client's Update Statics Blocks Function pointer.
NetworkManager * GetNetworkManager ()
Getter for the client Network Manager Pointer.
BaseFileManager * GetFileManager ()
Getter for the pointer to the client's File Manager.
Static Public Member Functions
static bool Initialize ()
Self Registering Class Initialize Method. Searches for client internal structures and pointers.
static void Configure ()
Self Registering Class Configure Method. This function is called first to create an instance of this class and make it available for other class instances to find.
Public Attributes
ClientRecvFunction m_pRecvFunction
Pointer to client's receive function.
ClientSendFunction m_pSendFunction
Pointer to client's send function.
ClientUpdateStaticBlocksFunction m_pUpdateBlocksFunction
Pointer to client's update blocks function.
Private Member Functions
bool checkLookupResult (void *address)
Checks to see if the resulting pointer exists in the memory space of the client.
Static Private Member Functions
static void ** FindNetworkStructureInstance ()
Searches for the client's network manager.
static ClientRecvFunction FindRecvFunction ()
Searches for the client's network receive function.
static ClientSendFunction FindSendFunction ()
Searches for the client's network send function.
static unsigned char * FindDrawMapThingieTable ()
Looks up the client's DrawMapThingie Structure.
static MapTileDefinition * FindMapDimensionStructure ()
Searches for the client's Map Dimension Structure. The Map Dimension Structure contains the map dimensions and wrapping coordinates for each client map.
static MapMinDisplay * FindMapMinCoordDisplayStructure ()
Searches for the client's Structure that holds the minimum coords to display on screen.
static int * FindClientDisplayedBlocksTable ()
Searches for the client's Display Blocks Table. This table contains a 64x64 array of blocks.
static CPlayerMobile * FindPlayerStructure ()
Searches for the client Player structure memory address.
static ClientUpdateStaticBlocksFunction FindUpdateBlocksFunction ()
Searches for the client function that updates onscreen statics.
static RefreshTerrainFunction FindRefreshTerrainFunction ()
Searches for the client function that refreshes the onscreen map graphics.
static CStaticObject ** FindMasterStaticsList ()
Searches for the client's Master Statics List Structure.
Private Attributes
void ** m_pNetworkStructureInstance
Pointer to client's Network Structure instance.
unsigned char * m_pMapThingieTable
Pointer to client's mapDrawThingie[64][64] (CDrawItem*)*.
MapTileDefinition * m_pMapDimensionsStructure
Pointer to client's Map Dimension Structure instance.
MapMinDisplay * m_pMapMinCoordDisplayStructure
Pointer to client's Mininum Coordinate Display Structure.
int * m_pClientDisplayedBlocksTable
Pointer to client's Displayed Blocks Table.
CPlayerMobile * m_pPlayerStructure
Pointer to client's Player Class Instance.
RefreshTerrainFunction m_pRefreshTerrainFunction
Pointer to client's Refresh Terrain function.
CStaticObject ** m_pMasterStaticsList
Pointer to client's Master Statics List.
DotNetHost * m_pDotNetHost
Pointer to Dot Net host (currently unused)
NetworkManager * m_pNetworkManager
Local Pointer to global network manager instance.
BaseFileManager * m_pFileManager
Local Pointer to global file manager instance.
Static Private Attributes
static void * BASE_ADDRESS = reinterpret_cast<void*>(0x400000)
Base address of client module in process virtual address space.
static const int CLIENT_IMAGE_MAX_SIZE = 0x300000
Maximum search size inside the client.
static unsigned char g_sendSignature1 [] = { 0x8D, 0x8B, 0x94, 0x00, 0x00, 0x00, 0xE8, 0xCC, 0xCC, 0xCC, 0xCC, 0x55, 0x8D, 0x8B, 0xBC, 0x00, 0x00, 0x00 }
Bytes used to search for client's send function.
static unsigned char g_sendSignature2 [] = { 0x0F, 0xB7, 0xD8, 0x0F, 0xB6, 0x06, 0x83, 0xC4, 0x04, 0x53, 0x50, 0x8D, 0x4F, 0x6C }
Bytes used to search for client's send function.
static unsigned char g_recvSignature1 [] = { 0x53, 0x56, 0x57, 0x8B, 0xF9, 0x8B, 0x0D, 0xCC, 0xCC, 0xCC, 0xCC, 0x33, 0xD2 }
Bytes used to search for client's receive function.
static unsigned char g_recvSignature2 [] = { 0xA1, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xC7, 0x05, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0x8B, 0x38, 0x8B, 0xCC, 0xBE }
Bytes used to search for client's receive function.
static unsigned char g_NetworkObjectSignature1 [] = { 0xA1, 0xCC, 0xCC, 0xCC, 0xCC, 0x8B, 0x0D, 0xCC, 0xCC, 0xCC, 0xCC, 0x8B, 0x16 }
Bytes used to search for client's Network Object.
static unsigned char g_NetworkObjectSignature2 [] = { 0xC7, 0x06, 0xCC, 0xCC, 0xCC, 0xCC, 0x89, 0x35, 0xCC, 0xCC, 0xCC, 0xCC, 0x8B, 0x4C, 0x24, 0x0C }
Bytes used to search for client's Network Object.
static unsigned char g_PlayerBaseSignature1 [] = { 0x66, 0x89, 0x71, 0x24, 0x8B, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC }
Bytes used to search for client's Player instance.
static unsigned char g_PlayerBaseSignature2 [] = { 0x66, 0x89, 0x71, 0x28, 0x8B, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC }
Bytes used to search for client's Player instance.
static unsigned char g_mapDimensionSignature [] = { 0x00, 0x1c, 0x00, 0x00, 0x00, 0x10, 0x00, 0x00 }
Bytes used to search for client's Map Dimension Structure.
static unsigned char g_aDrawMapThingieTableSig1 [] = { 0x83, 0xE1, 0x3F, 0x83, 0xE2, 0x3F, 0xC1, 0xE2, 0x06 }
Bytes used to search for client's Map Thingie Structure.
static unsigned char g_aDrawMapThingieTableSig2 [] = { 0x83, 0xE1, 0x3F, 0xC1, 0xE1, 0x06, 0x83, 0xE2, 0x3F }
Bytes used to search for client's Map Thingie Structure.
static unsigned char g_minClientDisplaySig1 [] = { 0xB8, 0xF1, 0xD8, 0xFF, 0xFF, 0x89, 0x3D, 0xCC, 0xCC, 0xCC, 0xCC, 0xA3, 0xCC, 0xCC, 0xCC, 0xCC, 0xA3 }
Bytes used to search for client's Client Display Structure.
static unsigned char g_minClientDisplaySig2 [] = { 0xB8, 0xF1, 0xD8, 0xFF, 0xFF, 0xCC, 0xCC, 0xCC, 0xCC, 0xCC, 0xA3, 0xCC, 0xCC, 0xCC, 0xCC, 0xA3 }
Bytes used to search for client's Client Display Structure.
static unsigned char g_minClientDisplaySig3 [] = { 0xB8, 0xF1, 0xD8, 0xFF, 0xFF, 0xA3, 0xCC, 0xCC, 0xCC, 0xCC, 0xA3 }
Bytes used to search for client's Client Display Structure.
static unsigned char g_updateBlocksSig1 [] = { 0xEE, 0xC1, 0xCC, 0x03, 0xC1, 0xCC, 0x03 }
Bytes used to search for client's Update Block function.
static unsigned char g_updateBlocksSig2 [] = { 0x2B, 0xD8, 0xC1, 0xCC, 0x03, 0xC1, 0xCC, 0x03 }
Bytes used to search for client's Update Block function.
static unsigned char g_refreshTerrainFunctionSig1 [] = { 0x75, 0xCC, 0x83, 0xCC, 0xFF, 0x74, 0xCC, 0xE8 }
Bytes used to search for client's Refresh Terrain function.
static unsigned char g_masterStaticsListSig1 [] = { 0x33, 0xf6, 0x68, 0x00, 0x00, 0xCC, 0x00, 0x89 }
Bytes used to search for client's Master Statics List Structure.
static unsigned char g_masterStaticsListSig2 [] = { 0x68, 0x40, 0xF9, 0x2F, 0x00, 0x89, 0x35 }
Bytes used to search for client's Master Statics List Structure.
static SelfRegisteringClass< Client > m_registration
Self Registration mechanism.
Detailed Description
This class knows about the client internals. This class assumes that it shares memory space with the actual client, therefor no calls to get memory from an external process are used.
Definition at line 54 of file Client.h.
Member Function Documentation
checkLookupResult()
bool Client::checkLookupResult (void * pAddress) private
Checks to see if the resulting pointer exists in the memory space of the client.
Returns
True if the memory address is valid, false otherwise
Definition at line 361 of file Client.cpp.
References Logger::g_pLogger, Logger::LogPrintTaskStatusResult(), and Logger::LogPrintWithoutDate().
Referenced by LookupClientInternalStructuresAndFunctions().
FindClientDisplayedBlocksTable()
int * Client::FindClientDisplayedBlocksTable () static private
Searches for the client's Display Blocks Table. This table contains a 64x64 array of blocks.
Returns
Pointer to an the clients Display Blocks Table
Definition at line 188 of file Client.cpp.
References MasterControlUtils::FindSignature().
Referenced by LookupClientInternalStructuresAndFunctions().
FindDrawMapThingieTable()
unsigned char * Client::FindDrawMapThingieTable () static private
Looks up the client's DrawMapThingie Structure.
Returns
Memory pointer to client's DrawMapThingie Structure
Definition at line 134 of file Client.cpp.
References MasterControlUtils::FindSignature().
Referenced by LookupClientInternalStructuresAndFunctions().
FindMapDimensionStructure()
MapTileDefinition * Client::FindMapDimensionStructure () static private
Searches for the client's Map Dimension Structure. The Map Dimension Structure contains the map dimensions and wrapping coordinates for each client map.
Returns
Pointer to the memory address of the client's Map Dimension Structure
Definition at line 350 of file Client.cpp.
References MasterControlUtils::FindSignatureOffset().
Referenced by LookupClientInternalStructuresAndFunctions().
FindMapMinCoordDisplayStructure()
MapMinDisplay * Client::FindMapMinCoordDisplayStructure () static private
Searches for the client's Structure that holds the minimum coords to display on screen.
Returns
Memory pointer to the Minimum Coord Display Structure
Definition at line 166 of file Client.cpp.
References MasterControlUtils::FindSignature().
Referenced by LookupClientInternalStructuresAndFunctions().
FindMasterStaticsList()
CStaticObject ** Client::FindMasterStaticsList () static private
Searches for the client's Master Statics List Structure.
Returns
Memory pointer to the Master Statics List Structure
Definition at line 150 of file Client.cpp.
References MasterControlUtils::FindSignature().
Referenced by LookupClientInternalStructuresAndFunctions().
FindNetworkStructureInstance()
void ** Client::FindNetworkStructureInstance () static private
Searches for the client's network manager.
Returns
Pointer to the memory address of the client's network manager
Definition at line 323 of file Client.cpp.
References MasterControlUtils::FindSignatureOffset().
Referenced by LookupClientInternalStructuresAndFunctions().
FindPlayerStructure()
CPlayerMobile * Client::FindPlayerStructure () static private
Searches for the client Player structure memory address.
Returns
Pointer to the memory address of the client player structure
Definition at line 252 of file Client.cpp.
References MasterControlUtils::FindSignatureOffset().
Referenced by LookupClientInternalStructuresAndFunctions().
FindRecvFunction()
Client::ClientRecvFunction Client::FindRecvFunction () static private
Searches for the client's network receive function.
Returns
Pointer to the memory address of the client's network receive function
Definition at line 296 of file Client.cpp.
References MasterControlUtils::FindSignatureOffset().
Referenced by LookupClientInternalStructuresAndFunctions().
FindRefreshTerrainFunction()
Client::RefreshTerrainFunction Client::FindRefreshTerrainFunction () static private
Searches for the client function that refreshes the onscreen map graphics.
Returns
Pointer to the refresh terrain client function
Definition at line 232 of file Client.cpp.
References MasterControlUtils::FindSignatureOffset().
Referenced by LookupClientInternalStructuresAndFunctions().
FindSendFunction()
Client::ClientSendFunction Client::FindSendFunction () static private
Searches for the client's network send function.
Returns
Pointer to the memory address of the client's network send function
Definition at line 269 of file Client.cpp.
References MasterControlUtils::FindSignatureOffset().
Referenced by LookupClientInternalStructuresAndFunctions().
FindUpdateBlocksFunction()
Client::ClientUpdateStaticBlocksFunction Client::FindUpdateBlocksFunction () static private
Searches for the client function that updates onscreen statics.
Returns
Pointer to the UpdateBlocks client function
Definition at line 215 of file Client.cpp.
References MasterControlUtils::FindFunctionCall().
Referenced by LookupClientInternalStructuresAndFunctions().
GetFileManager()
BaseFileManager * Client::GetFileManager ()
Getter for the pointer to the client's File Manager.
Returns
pointer to the client's File Manager
Definition at line 605 of file Client.cpp.
References m_pFileManager.
Referenced by ClientRedirections::OnCloseHandle(), ClientRedirections::OnCreateFileA(), ClientRedirections::OnCreateFileARunOnce(), ClientRedirections::OnCreateFileMappingA(), and ClientRedirections::OnMapViewOfFile().
GetNetworkManager()
NetworkManager * Client::GetNetworkManager ()
Getter for the client Network Manager Pointer.
Returns
pointer to the client's Network Manager
Definition at line 595 of file Client.cpp.
References m_pNetworkManager.
getPlayerMobile()
CPlayerMobile * Client::getPlayerMobile ()
Getter for the pointer to the client Player structure.
Returns
Client Player Structure Pointer
Definition at line 585 of file Client.cpp.
References m_pPlayerStructure.
Initialize()
bool Client::Initialize () static
Self Registering Class Initialize Method. Searches for client internal structures and pointers.
Returns
True if all client structures are found
Definition at line 52 of file Client.cpp.
References g_aDrawMapThingieTableSig1, g_aDrawMapThingieTableSig2, g_mapDimensionSignature, g_masterStaticsListSig1, g_masterStaticsListSig2, g_minClientDisplaySig1, g_minClientDisplaySig2, g_minClientDisplaySig3, g_NetworkObjectSignature1, g_NetworkObjectSignature2, g_PlayerBaseSignature1, g_PlayerBaseSignature2, Logger::g_pLogger, UltimaLive::g_pUltimaLive, g_recvSignature1, g_recvSignature2, g_refreshTerrainFunctionSig1, g_sendSignature1, g_sendSignature2, g_updateBlocksSig1, g_updateBlocksSig2, Logger::LogPrint(), Logger::LogPrintError(), UltimaLive::Lookup(), LookupClientInternalStructuresAndFunctions(), m_pFileManager, and m_pNetworkManager.
LookupClientInternalStructuresAndFunctions()
bool Client::LookupClientInternalStructuresAndFunctions ()
Search out all internal structure addresses.
Returns
true if all pointers and internal structures are found
Definition at line 406 of file Client.cpp.
References checkLookupResult(), FindClientDisplayedBlocksTable(), FindDrawMapThingieTable(), FindMapDimensionStructure(), FindMapMinCoordDisplayStructure(), FindMasterStaticsList(), FindNetworkStructureInstance(), FindPlayerStructure(), FindRecvFunction(), FindRefreshTerrainFunction(), FindSendFunction(), FindUpdateBlocksFunction(), Logger::g_pLogger, Logger::LogPrint(), Logger::LogPrintWithoutDate(), m_pClientDisplayedBlocksTable, m_pMapDimensionsStructure, m_pMapMinCoordDisplayStructure, m_pMapThingieTable, m_pMasterStaticsList, m_pNetworkStructureInstance, m_pPlayerStructure, m_pRecvFunction, m_pRefreshTerrainFunction, m_pSendFunction, and m_pUpdateBlocksFunction.
Referenced by Initialize().
refreshClientStatics()
void Client::refreshClientStatics (uint32_t blockNumber)
Refreshes statics on the client screen for a given block.
Parameters
blockNumber block number to refresh
Definition at line 489 of file Client.cpp.
References Logger::g_pLogger, Logger::LogPrint(), m_pClientDisplayedBlocksTable, m_pMapDimensionsStructure, m_pMapMinCoordDisplayStructure, m_pMasterStaticsList, and ClientRedirections::OnUpdateStaticBlocks().
Referenced by Atlas::onUpdateStatics().
SendPacketToClient()
void Client::SendPacketToClient (unsigned char * pBuffer)
Sends an array of bytes to the client using the clients receive function.
Parameters
pBuffer pointer to byte array
Definition at line 564 of file Client.cpp.
References Logger::g_pLogger, Logger::LogPrint(), m_pNetworkStructureInstance, and m_pRecvFunction.
Referenced by NetworkManager::sendPacketToClient().
SendPacketToServer()
void Client::SendPacketToServer (unsigned char * pBuffer)
Sends an array of bytes to the server using the clients send function.
Parameters
pBuffer pointer to byte array
Definition at line 554 of file Client.cpp.
References m_pNetworkStructureInstance, and m_pSendFunction.
Referenced by NetworkManager::sendPacketToServer().
SetMapDimensions()
void Client::SetMapDimensions (MapTileDefinition definition)
Updates the client's map dimensions.
Parameters
definition New map definition set
Definition at line 575 of file Client.cpp.
References m_pMapDimensionsStructure.
Referenced by Atlas::LoadMap().
The documentation for this class was generated from the following files:
UltimaLive/Client.h
UltimaLive/Client.cpp