UltimaLive: Logger Class Reference
Logger Class Reference abstract
Abstract class that handles all logging.
#include <Debug.h>
Public Member Functions
virtual void LogPrint (const char *,...)=0
Logs a message to the console log with an [INFO] printed in front of it.
virtual void LogPrintWarning (const char *,...)=0
Logs a message to the console log with an [WARNING] printed in front of it.
virtual void LogPrintError (const char *,...)=0
Logs a message to the console log with an [ERROR] printed in front of it.
virtual void LogLastErrorMessage ()=0
Logs the last error message reported by Windows with a [WINDOWS ERROR] printed in front of it.
virtual void LogPacketToServer (const char *,...)=0
Logs a packet to the console with appropriate colors.
virtual void LogPacketToClient (const char *,...)=0
Logs a packet to the console with appropriate colors.
virtual void LogPrintWithoutDate (const char *,...)=0
Logs a message to the console log without any logger decoration.
virtual void LogPrintWithoutDateWarning (const char *,...)=0
Logs a warning message to the console log without date information.
virtual void LogPrintWithoutDateError (const char *,...)=0
Logs an error message to the console log without date information.
virtual void LogPrintTaskStatusResult (bool status)=0
Logs a message with a success or failure status message.
virtual void InitializeLogger ()=0
Spawns a console window if one does not exist. Redirects stdout to the console.
Static Public Attributes
static Logger * g_pLogger = new ConsoleLogger()
Global Logger Instance.
Detailed Description
Abstract class that handles all logging.
Definition at line 49 of file Debug.h.
Member Function Documentation
LogPrintTaskStatusResult()
virtual void Logger::LogPrintTaskStatusResult (bool status) pure virtual
Logs a message with a success or failure status message.
Parameters
status True for success, false for failure
Implemented in ConsoleLogger, and ConsoleLogger.
Referenced by Client::checkLookupResult(), BaseFileManager::checkValidMemoryAllocated(), NetworkManager::Initialize(), and ClientRedirections::InstallClientHooks().
The documentation for this class was generated from the following files:
UltimaLive/Debug.h
UltimaLive/Debug.cpp