UltimaLive: ConsoleLogger Class Reference
ConsoleLogger Class Reference
ConsoleLogger class handles console allocation, and all logging going to the console.
#include <Debug.h>
Public Types
enum Color {
DARKBLUE = 1, DARKGREEN, DARKTEAL, DARKRED,
DARKPINK, DARKYELLOW, GRAY, DARKGRAY,
BLUE, GREEN, TEAL, RED,
PINK, YELLOW, WHITE
}
Flags corresponding to console color.
Public Member Functions
void LogPrint (const char *,...)
Logs a message to the console log with an [INFO] printed in front of it.
void LogPrintWarning (const char *,...)
Logs a message to the console log with an [WARNING] printed in front of it.
void LogPrintError (const char *,...)
Logs a message to the console log with an [ERROR] printed in front of it.
void LogPacketToServer (const char *,...)
Logs a packet to the console with appropriate colors.
void LogPacketToClient (const char *,...)
Logs a packet to the console with appropriate colors.
void LogLastErrorMessage ()
Logs the last error message reported by Windows with a [WINDOWS ERROR] printed in front of it.
void LogPrintWithoutDate (const char *,...)
Logs a message to the console log without any logger decoration.
void LogPrintWithoutDateWarning (const char *,...)
Logs a warning message to the console log without date information.
void LogPrintWithoutDateError (const char *,...)
Logs an error message to the console log without date information.
void LogPrintTaskStatusResult (bool status)
Logs a message with a success or failure status message.
void InitializeLogger ()
Spawns a console window if one does not exist. Redirects stdout to the console.
void LogPrint (const char *,...)
Logs a message to the console log with an [INFO] printed in front of it.
void LogPrintWarning (const char *,...)
Logs a message to the console log with an [WARNING] printed in front of it.
void LogPrintError (const char *,...)
Logs a message to the console log with an [ERROR] printed in front of it.
void LogPacketToServer (const char *,...)
Logs a packet to the console with appropriate colors.
void LogPacketToClient (const char *,...)
Logs a packet to the console with appropriate colors.
void LogLastErrorMessage ()
Logs the last error message reported by Windows with a [WINDOWS ERROR] printed in front of it.
void LogPrintWithoutDate (const char *,...)
Logs a message to the console log without any logger decoration.
void LogPrintWithoutDateWarning (const char *,...)
Logs a warning message to the console log without date information.
void LogPrintWithoutDateError (const char *,...)
Logs an error message to the console log without date information.
void LogPrintTaskStatusResult (bool)
Logs a message with a success or failure status message.
void InitializeLogger ()
Spawns a console window if one does not exist. Redirects stdout to the console.
Private Member Functions
void printCurrentDateTime ()
Logs the current date and time to the console.
Private Attributes
HANDLE m_hConOut
Console Handle.
Additional Inherited Members
Static Public Attributes inherited from Logger
static Logger * g_pLogger = new ConsoleLogger()
Global Logger Instance.
Detailed Description
ConsoleLogger class handles console allocation, and all logging going to the console.
Definition at line 118 of file Debug.h.
Member Function Documentation
LogPacketToClient()
void ConsoleLogger::LogPacketToClient (const char * fmt, ...) virtual
Logs a packet to the console with appropriate colors.
Parameters
fmt Printf format for the log statement
... arguments to be passed to the printf command
Implements Logger.
Definition at line 81 of file Debug.cpp.
References m_hConOut, and printCurrentDateTime().
LogPacketToServer()
void ConsoleLogger::LogPacketToServer (const char * fmt, ...) virtual
Logs a packet to the console with appropriate colors.
Parameters
fmt Printf format for the log statement
... arguments to be passed to the printf command
Implements Logger.
Definition at line 106 of file Debug.cpp.
References m_hConOut, and printCurrentDateTime().
LogPrint()
void ConsoleLogger::LogPrint (const char * fmt, ...) virtual
Logs a message to the console log with an [INFO] printed in front of it.
Parameters
fmt Printf format for the log statement
... arguments to be passed to the printf command
Implements Logger.
Definition at line 131 of file Debug.cpp.
References m_hConOut, and printCurrentDateTime().
LogPrintError()
void ConsoleLogger::LogPrintError (const char * fmt, ...) virtual
Logs a message to the console log with an [ERROR] printed in front of it.
Parameters
fmt Printf format for the log statement
... arguments to be passed to the printf command
Implements Logger.
Definition at line 183 of file Debug.cpp.
References m_hConOut, and printCurrentDateTime().
LogPrintTaskStatusResult() [1/2]
void ConsoleLogger::LogPrintTaskStatusResult (bool status) virtual
Logs a message with a success or failure status message.
Parameters
status True for success, false for failure
Implements Logger.
Definition at line 308 of file Debug.cpp.
References m_hConOut.
LogPrintTaskStatusResult() [2/2]
void ConsoleLogger::LogPrintTaskStatusResult (bool status) inline virtual
Logs a message with a success or failure status message.
Parameters
status True for success, false for failure
Implements Logger.
Definition at line 154 of file Debug.h.
LogPrintWarning()
void ConsoleLogger::LogPrintWarning (const char * fmt, ...) virtual
Logs a message to the console log with an [WARNING] printed in front of it.
Parameters
fmt Printf format for the log statement
... arguments to be passed to the printf command
Implements Logger.
Definition at line 156 of file Debug.cpp.
References m_hConOut, and printCurrentDateTime().
LogPrintWithoutDate()
void ConsoleLogger::LogPrintWithoutDate (const char * fmt, ...) virtual
Logs a message to the console log without any logger decoration.
Parameters
fmt Printf format for the log statement
... arguments to be passed to the printf command
Implements Logger.
Definition at line 240 of file Debug.cpp.
References m_hConOut.
LogPrintWithoutDateError()
void ConsoleLogger::LogPrintWithoutDateError (const char * fmt, ...) virtual
Logs an error message to the console log without date information.
Parameters
fmt Printf format for the log statement
... arguments to be passed to the printf command
Implements Logger.
Definition at line 286 of file Debug.cpp.
References m_hConOut.
LogPrintWithoutDateWarning()
void ConsoleLogger::LogPrintWithoutDateWarning (const char * fmt, ...) virtual
Logs a warning message to the console log without date information.
Parameters
fmt Printf format for the log statement
... arguments to be passed to the printf command
Implements Logger.
Definition at line 263 of file Debug.cpp.
References m_hConOut.
The documentation for this class was generated from the following files:
UltimaLive/Debug.h
UltimaLive/Debug.cpp