UltimaLive: MasterControlUtils Class Reference
MasterControlUtils Class Reference
Utility class for searching for a process's internal structures.
#include <MasterControlUtils.h>
Static Public Member Functions
static void * FindSignatureOffset (void *pBuffer, unsigned int bufferLen, unsigned char *sigBuffer, unsigned int sigLen)
Search memory for specified byte signature. Note that 0xCC is a wildcard byte, it matches anything. A more proper way to do this is one pointer to a signature and another pointer to wildcard flags, but this is simpler and works well. Returns a pointer to the beginning of the signature match. Returns 0 on no match.
static void * FindFunctionCall (void *pBuffer, int bufferSize, unsigned char *pSignature, int signatureSize)
Does a forward search for a function.
static void * FindSignatureOffsetBackwards (void *pData, unsigned int searchLen, unsigned char *sigBuffer, unsigned int sigLen)
Does a reverse search for a series of bytes.
static void * FindSignature (void *pBuffer, int bufferSize, unsigned char *pSignature, int signatureSize, int offset, int &structureSizeOut, int structureSizeOffset)
Does a forward search for an structure containing a pointer.
static void * FindSignature (void *pBuffer, int bufferSize, unsigned char *pSignature, int signatureSize, int offset)
Does a forward search for an array of bytes.
Static Private Attributes
static unsigned char g_functionStartSig1 [] = { 0x55, 0x8B, 0xEC }
Function signature.
static unsigned char g_functionStartSig2 [] = { 0x90, 0x90, 0x6A }
Function signature.
Detailed Description
Utility class for searching for a process's internal structures.
Definition at line 35 of file MasterControlUtils.h.
Member Function Documentation
FindFunctionCall()
void * MasterControlUtils::FindFunctionCall (void * pBuffer, int bufferSize, unsigned char * pSignature, int signatureSize) static
Does a forward search for a function.
Parameters
pBuffer Pointer of data to be searched
bufferSize Maximum number of bytes to search
pSignature Array of bytes to search
signatureSize Length of search array in bytes
Returns
Pointer to function
Definition at line 75 of file MasterControlUtils.cpp.
References FindSignatureOffset(), FindSignatureOffsetBackwards(), g_functionStartSig1, and g_functionStartSig2.
Referenced by Client::FindUpdateBlocksFunction().
FindSignature() [1/2]
void * MasterControlUtils::FindSignature (void * pBuffer, int bufferSize, unsigned char * pSignature, int signatureSize, int offset, int & structureSizeOut, int structureSizeOffset) static
Does a forward search for an structure containing a pointer.
Parameters
pBuffer Pointer of data to be searched
bufferSize Maximum number of bytes to search
pSignature Array of bytes to search
signatureSize Length of search array in bytes
offset Offset from search result to structure
structureSizeOut reference to the structure size
structureSizeOffset offset to apply to the structure base address
Returns
Pointer to function
Definition at line 110 of file MasterControlUtils.cpp.
References FindSignatureOffset().
Referenced by Client::FindClientDisplayedBlocksTable(), Client::FindDrawMapThingieTable(), Client::FindMapMinCoordDisplayStructure(), and Client::FindMasterStaticsList().
FindSignature() [2/2]
void * MasterControlUtils::FindSignature (void * pBuffer, int bufferSize, unsigned char * pSignature, int signatureSize, int offset) static
Does a forward search for an array of bytes.
Parameters
pBuffer Pointer of data to be searched
bufferSize Maximum number of bytes to search
pSignature Array of bytes to search
signatureSize Length of search array in bytes
offset Offset to add to result
Returns
Pointer to function
Definition at line 135 of file MasterControlUtils.cpp.
References FindSignatureOffset().
FindSignatureOffset()
void * MasterControlUtils::FindSignatureOffset (void * pBuffer, unsigned int bufferLen, unsigned char * sigBuffer, unsigned int sigLen) static
Search memory for specified byte signature. Note that 0xCC is a wildcard byte, it matches anything. A more proper way to do this is one pointer to a signature and another pointer to wildcard flags, but this is simpler and works well. Returns a pointer to the beginning of the signature match. Returns 0 on no match.
Parameters
pBuffer Pointer of data to be searched
bufferLen Maximum number of bytes to search
sigBuffer Array of bytes to search
sigLen Length of search array in bytes
Returns
Pointer to function
Definition at line 161 of file MasterControlUtils.cpp.
Referenced by FindFunctionCall(), Client::FindMapDimensionStructure(), Client::FindNetworkStructureInstance(), Client::FindPlayerStructure(), Client::FindRecvFunction(), Client::FindRefreshTerrainFunction(), Client::FindSendFunction(), and FindSignature().
FindSignatureOffsetBackwards()
void * MasterControlUtils::FindSignatureOffsetBackwards (void * pData, unsigned int searchLen, unsigned char * sigBuffer, unsigned int sigLen) static
Does a reverse search for a series of bytes.
Parameters
pData Pointer of data to be searched
searchLen Maximum number of bytes to search
sigBuffer Array of bytes to search
sigLen Length of search array in bytes
Returns
Pointer to memory address
Definition at line 36 of file MasterControlUtils.cpp.
Referenced by FindFunctionCall().
The documentation for this class was generated from the following files:
UltimaLive/MasterControlUtils.h
UltimaLive/MasterControlUtils.cpp