UltimaLive: BaseFileManager Class Reference
BaseFileManager Class Reference abstract
The responsibility of the file manager is to handle the custom file formats that the client may employ. The main reason for using a factory pattern here is because the client seems to be in a transistion phase where old mul files are being converted to the new uop format. The conversion has not happened all at once, so the factory will allow the use of different file managers based on the client version.
#include <BaseFileManager.h>
Public Member Functions
BaseFileManager ()
BaseFileManager constructor.
virtual HANDLE WINAPI OnCreateFileA (__in LPCSTR lpFileName, __in DWORD dwDesiredAccess, __in DWORD dwShareMode, __in_opt LPSECURITY_ATTRIBUTES lpSecurityAttributes, __in DWORD dwCreationDisposition, __in DWORD dwFlagsAndAttributes, __in_opt HANDLE hTemplateFile)
Called when the client calls CreateFileA. Caches object handles needed by filemanagers.
virtual LPVOID WINAPI OnMapViewOfFile (__in HANDLE hFileMappingObject, __in DWORD dwDesiredAccess, __in DWORD dwFileOffsetHigh, __in DWORD dwFileOffsetLow, __in SIZE_T dwNumberOfBytesToMap)
Called in place of client's MapViewOfFile. Stores mapping address if it corresponds to a file that UltimaLive uses.
virtual HANDLE WINAPI OnCreateFileMappingA (__in HANDLE hFile, __in_opt LPSECURITY_ATTRIBUTES lpAttributes, __in DWORD flProtect, __in DWORD dwMaximumSizeHigh, __in DWORD dwMaximumSizeLow, __in_opt LPCSTR lpName)
Called when the client calls createfilemapping. Stores a file mapping with a matching fileset if its a file UltimaLive Tracks.
virtual BOOL WINAPI OnCloseHandle (_In_ HANDLE hObject)
Called when the client calls its CloseHandle function. Removes filenames from the list of open handles.
virtual unsigned char * readStaticsBlock (uint32_t mapNumber, uint32_t blockNum, uint32_t &rNumberOfBytesOut)
reads data corresponding to all statics contained in one map block
virtual bool writeStaticsBlock (uint8_t mapNumber, uint32_t blockNum, uint8_t *pBlockData, uint32_t length)
Writes data corresponding to the statics in a map block out to memory and to the UltimaLive file cache.
virtual bool Initialize ()
Initializes the BaseFileManager by allocating memory internally in the client for maps, statics, and indices.
virtual void LoadMap (uint8_t mapNumber)=0
Load a map.
virtual void InitializeShardMaps (std::string shardIdentifier, std::map< uint32_t, MapDefinition > definitions)
Initializes a shards maps by creating or copying new maps into the UltimaLive file cache.
virtual void onLogout ()
handles client logout and prepares UltimaLive for a new login
virtual bool updateLandBlock (uint8_t mapNumber, uint32_t blockNum, uint8_t *pData)
updates a land block in memory and in UltimaLive's map cache on disk
virtual unsigned char * readLandBlock (uint8_t mapNumber, uint32_t blockNum)
Reads a land block and returns a pointer to the newly allocated memory. Caller is responsible for memory cleanup.
virtual unsigned char * seekLandBlock (uint8_t mapNumber, uint32_t blockNum)=0
Seeks a land block in map file.
Static Public Member Functions
static void copyFile (std::string sourceFilePath, std::string destFilePath, ProgressBarDialog *pProgress)
Copy a file from one location to another.
Static Public Attributes
static const int MAP_MEMORY_SIZE = 100000000
Memory to allocate for the largest possible map file.
static const int STAIDX_MEMORY_SIZE = 10000000
Memory to allocate for the largest possible statics index file.
static const int STATICS_MEMORY_SIZE = 200000000
Memory to allocate for the largets possible statics file.
Protected Member Functions
std::string getUltimaLiveSavePath ()
Gets the UltimaLive cache path for the platform.
virtual bool createNewPersistentMap (std::string pathWithoutFilename, uint8_t mapNumber, uint32_t numHorizontalBlocks, uint32_t numVerticalBlocks)
Creates a new blank map in the map store from scratch.
bool checkValidMemoryAllocated (void *pBuffer)
Checks to see if UltimaLive has allocated a valid pool of memory.
Protected Attributes
std::map< std::string, ClientFileHandleSet * > m_files
Maps the base map name to the set of handles for the corresponding files (map#.mul, staidx#.mul statics#.mul)
uint8_t * m_pMapPool
Pointer to the memory pool used to load and unload maps.
uint8_t * m_pStaticsPool
Pointer to the memory pool used to load and unload statics.
uint8_t * m_pStaticsPoolEnd
Pointer to the end of the statics memory pool.
uint8_t * m_pStaidxPool
Pointer to the statics index memory pool.
uint8_t * m_pStaidxPoolEnd
Pointer to the end of the statics index memory pool.
std::string m_shardIdentifier
Unique shard identifier.
std::ofstream * m_pMapFileStream
Pointer to map file stream.
std::ofstream * m_pStaidxFileStream
Pointer to statics index file stream.
std::ofstream * m_pStaticsFileStream
Pointer to statics file stream.
ProgressBarDialog * m_pProgressDlg
Pointer to the progress bar dialog.
Detailed Description
The responsibility of the file manager is to handle the custom file formats that the client may employ. The main reason for using a factory pattern here is because the client seems to be in a transistion phase where old mul files are being converted to the new uop format. The conversion has not happened all at once, so the factory will allow the use of different file managers based on the client version.
The file manager will redirect the client to open files from alternate folders, alter files that are on disk, create new map files, defragment files, and any other filesystem type tasks.
Definition at line 56 of file BaseFileManager.h.
Member Function Documentation
checkValidMemoryAllocated()
bool BaseFileManager::checkValidMemoryAllocated (void * pBuffer) protected
Checks to see if UltimaLive has allocated a valid pool of memory.
Returns
true on success
Definition at line 774 of file BaseFileManager.cpp.
References Logger::g_pLogger, Logger::LogLastErrorMessage(), Logger::LogPrintError(), Logger::LogPrintTaskStatusResult(), and m_pMapPool.
Referenced by Initialize().
copyFile()
void BaseFileManager::copyFile (std::string sourceFilePath, std::string destFilePath, ProgressBarDialog * pProgress) static
Copy a file from one location to another.
Parameters
sourceFilePath source path
destFilePath destination path
pProgress progress bar handle
Definition at line 409 of file BaseFileManager.cpp.
References ProgressBarDialog::setProgress().
Referenced by FileManager_7_0_29_2::InitializeShardMaps(), and InitializeShardMaps().
createNewPersistentMap()
bool BaseFileManager::createNewPersistentMap (std::string pathWithoutFilename, uint8_t mapNumber, uint32_t numHorizontalBlocks, uint32_t numVerticalBlocks) protected virtual
Creates a new blank map in the map store from scratch.
Parameters
pathWithoutFilename location to save file
mapNumber Number to be appended to the new filename
numHorizontalBlocks Number of horizontal blocks for the new map
numVerticalBlocks Number of vertical blocks for the new map
Returns
true on success
Definition at line 326 of file BaseFileManager.cpp.
References Logger::g_pLogger, and Logger::LogPrint().
Referenced by FileManager_7_0_29_2::InitializeShardMaps(), and InitializeShardMaps().
getUltimaLiveSavePath()
std::string BaseFileManager::getUltimaLiveSavePath () protected
Gets the UltimaLive cache path for the platform.
Returns
UltimaLive cache path
Definition at line 596 of file BaseFileManager.cpp.
Referenced by Initialize(), FileManager_7_0_29_2::InitializeShardMaps(), InitializeShardMaps(), FileManager::LoadMap(), and FileManager_7_0_29_2::LoadMap().
Initialize()
bool BaseFileManager::Initialize () virtual
Initializes the BaseFileManager by allocating memory internally in the client for maps, statics, and indices.
Returns
true on success
Reimplemented in FileManager_7_0_29_2, and FileManager.
Definition at line 259 of file BaseFileManager.cpp.
References checkValidMemoryAllocated(), Logger::g_pLogger, getUltimaLiveSavePath(), Logger::LogPrintWithoutDate(), m_pMapPool, m_pStaidxPool, m_pStaticsPool, m_pStaticsPoolEnd, MAP_MEMORY_SIZE, STAIDX_MEMORY_SIZE, and STATICS_MEMORY_SIZE.
Referenced by FileManagerFactory::Initialize(), FileManager::Initialize(), and FileManager_7_0_29_2::Initialize().
InitializeShardMaps()
void BaseFileManager::InitializeShardMaps (std::string shardIdentifier, std::map< uint32_t, MapDefinition > mapDefinitions) virtual
Initializes a shards maps by creating or copying new maps into the UltimaLive file cache.
Parameters
shardIdentifier Unique shard identifier
mapDefinitions Map definitions for the shard
Reimplemented in FileManager_7_0_29_2.
Definition at line 468 of file BaseFileManager.cpp.
References copyFile(), createNewPersistentMap(), Logger::g_pLogger, Utils::GetCurrentPathWithoutFilename(), getUltimaLiveSavePath(), ProgressBarDialog::hide(), Logger::LogPrint(), m_pProgressDlg, m_shardIdentifier, ProgressBarDialog::setMessage(), ProgressBarDialog::setProgress(), and ProgressBarDialog::show().
Referenced by Atlas::LoadMap().
LoadMap()
virtual void BaseFileManager::LoadMap (uint8_t mapNumber) pure virtual
Load a map.
Parameters
mapNumber Map number
Implemented in FileManager_7_0_29_2, and FileManager.
Referenced by Atlas::LoadMap().
OnCloseHandle()
BOOL WINAPI BaseFileManager::OnCloseHandle (_In_ HANDLE hObject) virtual
Called when the client calls its CloseHandle function. Removes filenames from the list of open handles.
Parameters
hObject Object Handle
Returns
true on success
Definition at line 634 of file BaseFileManager.cpp.
References m_files.
Referenced by ClientRedirections::OnCloseHandle().
OnCreateFileA()
HANDLE WINAPI BaseFileManager::OnCreateFileA (__in LPCSTR lpFileName, __in DWORD dwDesiredAccess, __in DWORD dwShareMode, __in_opt LPSECURITY_ATTRIBUTES lpSecurityAttributes, __in DWORD dwCreationDisposition, __in DWORD dwFlagsAndAttributes, __in_opt HANDLE hTemplateFile) virtual
Called when the client calls CreateFileA. Caches object handles needed by filemanagers.
Parameters
lpFileName The name of the file or device to be created or opened.
dwDesiredAccess The requested access to the file or device, which can be summarized as read, write, both or neither.
dwShareMode The requested sharing mode of the file or device, which can be read, write, both, delete, all of these, or none.
lpSecurityAttributes A pointer to a SECURITY_ATTRIBUTES structure that contains two separate but related data members.
dwCreationDisposition An action to take on a file or device that exists or does not exist.
dwFlagsAndAttributes The file or device attributes and flags, FILE_ATTRIBUTE_NORMAL being the most common default value for files.
hTemplateFile A valid handle to a template file with the GENERIC_READ access right.
Returns
Object Handle
Definition at line 661 of file BaseFileManager.cpp.
References Utils::getFilenameFromPath(), and m_files.
Referenced by ClientRedirections::OnCreateFileA(), and ClientRedirections::OnCreateFileARunOnce().
OnCreateFileMappingA()
HANDLE WINAPI BaseFileManager::OnCreateFileMappingA (__in HANDLE hFile, __in_opt LPSECURITY_ATTRIBUTES lpAttributes, __in DWORD flProtect, __in DWORD dwMaximumSizeHigh, __in DWORD dwMaximumSizeLow, __in_opt LPCSTR lpName) virtual
Called when the client calls createfilemapping. Stores a file mapping with a matching fileset if its a file UltimaLive Tracks.
Parameters
hFile A handle to the file from which to create a file mapping object.
lpAttributes A pointer to a SECURITY_ATTRIBUTES structure that determines whether a returned handle can be inherited by child processes.
flProtect Specifies the page protection of the file mapping object.
dwMaximumSizeHigh The high-order DWORD of the maximum size of the file mapping object.
dwMaximumSizeLow The low-order DWORD of the maximum size of the file mapping object.
lpName The name of the file mapping object.
Returns
New File's Handle
Definition at line 699 of file BaseFileManager.cpp.
References ClientFileHandleSet::m_createFileMappingHandle, and m_files.
Referenced by ClientRedirections::OnCreateFileMappingA().
OnMapViewOfFile()
LPVOID WINAPI BaseFileManager::OnMapViewOfFile (__in HANDLE hFileMappingObject, __in DWORD dwDesiredAccess, __in DWORD dwFileOffsetHigh, __in DWORD dwFileOffsetLow, __in SIZE_T dwNumberOfBytesToMap) virtual
Called in place of client's MapViewOfFile. Stores mapping address if it corresponds to a file that UltimaLive uses.
Parameters
hFileMappingObject A handle to a file mapping object.
dwDesiredAccess The type of access to a file mapping object, which determines the protection of the pages.
dwFileOffsetHigh A high-order DWORD of the file offset where the view begins.
dwFileOffsetLow A low-order DWORD of the file offset where the view is to begin.
dwNumberOfBytesToMap The number of bytes of a file mapping to map to the view.
Returns
The starting address of the mapped view
Reimplemented in FileManager_7_0_29_2, and FileManager.
Definition at line 740 of file BaseFileManager.cpp.
References m_files, and ClientFileHandleSet::m_mapFileViewHandle.
Referenced by ClientRedirections::OnMapViewOfFile().
readLandBlock()
unsigned char * BaseFileManager::readLandBlock (uint8_t mapNumber, uint32_t blockNum) virtual
Reads a land block and returns a pointer to the newly allocated memory. Caller is responsible for memory cleanup.
Parameters
mapNumber number corresponding to the map to search
blockNum number corresponding to the block in the map
Returns
Pointer to the block memory
Definition at line 41 of file BaseFileManager.cpp.
References seekLandBlock().
Referenced by Atlas::getBlockCrc().
readStaticsBlock()
unsigned char * BaseFileManager::readStaticsBlock (uint32_t mapNumber, uint32_t blockNum, uint32_t & rNumberOfBytesOut) virtual
reads data corresponding to all statics contained in one map block
Parameters
mapNumber Map Number
blockNum Block Number
rNumberOfBytesOut number of bytes read
Returns
pointer to memory containing statics in the block
Definition at line 132 of file BaseFileManager.cpp.
References m_pStaidxPool, and m_pStaticsPool.
Referenced by Atlas::getBlockCrc().
seekLandBlock()
virtual unsigned char* BaseFileManager::seekLandBlock (uint8_t mapNumber, uint32_t blockNum) pure virtual
Seeks a land block in map file.
Parameters
mapNumber Map Number
blockNum Block Number
Returns
Pointer to land block memory
Implemented in FileManager_7_0_29_2, and FileManager.
Referenced by readLandBlock(), and updateLandBlock().
updateLandBlock()
bool BaseFileManager::updateLandBlock (uint8_t mapNumber, uint32_t blockNum, uint8_t * pLandData) virtual
updates a land block in memory and in UltimaLive's map cache on disk
Parameters
mapNumber number corresponding to the map (e.g. map0.mul)
blockNum number corresponding to the map block to be updated
pLandData pointer to new data to replace the existing land data
Returns
True on success
Definition at line 66 of file BaseFileManager.cpp.
References Logger::g_pLogger, Logger::LogPrint(), m_pMapFileStream, and seekLandBlock().
Referenced by Atlas::onUpdateLand().
writeStaticsBlock()
bool BaseFileManager::writeStaticsBlock (uint8_t mapNumber, uint32_t blockNum, uint8_t * pBlockData, uint32_t updatedStaticsLength) virtual
Writes data corresponding to the statics in a map block out to memory and to the UltimaLive file cache.
Parameters
mapNumber Map Number
blockNum Block number
pBlockData Pointer tot he new block data
updatedStaticsLength Number of bytes in the new data
Returns
true on success
Definition at line 167 of file BaseFileManager.cpp.
References Logger::g_pLogger, Logger::LogPrint(), m_pStaidxFileStream, m_pStaidxPool, m_pStaticsFileStream, m_pStaticsPool, m_pStaticsPoolEnd, and STATICS_MEMORY_SIZE.
Referenced by Atlas::onUpdateStatics().
The documentation for this class was generated from the following files:
UltimaLive/FileSystem/BaseFileManager.h
UltimaLive/FileSystem/BaseFileManager.cpp