UltimaLive: Atlas Class Reference
Atlas Class Reference
Manages changing client maps.
#include <Atlas.h>
Public Member Functions
Atlas ()
Atlast Constructor.
uint16_t * GetGroupOfBlockCrcs (uint32_t mapNumber, uint32_t blockNumber)
Gets CRCs for the 25 blocks surrounding the current players position.
void LoadMap (uint8_t map)
Loads a map based on map number.
uint8_t getCurrentMap ()
Getter for the current map number.
Static Public Member Functions
static uint16_t fletcher16 (uint8_t *pBlockData, uint8_t *pStaticsData, uint32_t staticsLength)
Calculates a CRC using the combined land and statics data.
static bool Initialize ()
Initializes Atlas class. Gets pointers to the client global pointer and subscribes to packets.
static void Configure ()
Class Registration Configuration function that creates the Atlas global and registers it.
Protected Member Functions
void onBeforeMapChange (uint8_t &rMap)
Changes the client's map to map1 so that the client will load a map0 and refresh the view Map0 and Map1 point to the same place internally. This is a way of making sure the client actually performs the load.
void onMapChange (uint8_t &rMap)
Loads the specified map.
void onHashQuery (uint32_t blockNumber, uint8_t mapNumber)
Responds to a server hash query for a particular map block (land and statics)
void onRefreshClientView ()
Refreshes the client's view to match the current state of the map.
void onUpdateMapDefinitions (std::vector< MapDefinition > definitions)
Updates map definitions as received from the server.
void onUpdateStatics (uint8_t mapNumber, uint32_t blockNumber, uint8_t *pData, uint32_t length)
Updates a static block by calling the filemanager and then refreshes the client.
void onShardIdentifierUpdate (std::string shardIdentifier)
setter for Shard Identifier
void onUpdateLand (uint8_t mapNumber, uint32_t blockNumber, uint8_t *pLandData)
@ Updates a land block on a given map
void onLogout ()
Calls file manager logout handler.
uint16_t getBlockCrc (uint32_t mapNumber, uint32_t blockNumber)
Looks up the memory blocks for a specified block number and map number, returns the CRC of the block.
Protected Attributes
std::map< uint32_t, MapDefinition > m_mapDefinitions
Map linking map indices to map definitions.
uint8_t m_currentMap
Current map in client memory.
NetworkManager * m_pNetworkManager
Pointer to Network Manager.
BaseFileManager * m_pFileManager
Pointer to File Manager.
Client * m_pClient
Pointer to Client Manager.
std::string m_shardIdentifier
Unique Shard Identifier.
bool m_firstMapLoad
Indicates if the map has been loaded in the past.
Static Protected Attributes
static int32_t BLOCK_POSITION_OFFSETS [5] = { -2, -1, 0, 1, 2 }
Array of offsets used when calculating hashes.
Static Private Attributes
static SelfRegisteringClass< Atlas > m_registration
Class Self Registration mechanism.
Detailed Description
Manages changing client maps.
Definition at line 50 of file Atlas.h.
Member Function Documentation
fletcher16()
uint16_t Atlas::fletcher16 (uint8_t * pBlockData, uint8_t * pStaticsData, uint32_t staticsLength) static
Calculates a CRC using the combined land and statics data.
Parameters
pBlockData Pointer to the memory containing land data
pStaticsData Pointer to the memory containing statics data
staticsLength Number of bytes in the statics data
@ return 16 bit CRC
Definition at line 331 of file Atlas.cpp.
References BLOCK_POSITION_OFFSETS.
Referenced by getBlockCrc().
getBlockCrc()
uint16_t Atlas::getBlockCrc (uint32_t mapNumber, uint32_t blockNumber) protected
Looks up the memory blocks for a specified block number and map number, returns the CRC of the block.
Parameters
mapNumber Map Number
blockNumber Block Number
Definition at line 451 of file Atlas.cpp.
References fletcher16(), m_mapDefinitions, m_pFileManager, BaseFileManager::readLandBlock(), and BaseFileManager::readStaticsBlock().
Referenced by GetGroupOfBlockCrcs().
getCurrentMap()
uint8_t Atlas::getCurrentMap ()
Getter for the current map number.
Returns
Current map number
Definition at line 317 of file Atlas.cpp.
References m_currentMap.
GetGroupOfBlockCrcs()
uint16_t * Atlas::GetGroupOfBlockCrcs (uint32_t mapNumber, uint32_t blockNumber)
Gets CRCs for the 25 blocks surrounding the current players position.
Parameters
mapNumber Map Number
blockNumber Number of the block containing the current player position
Returns
Array of 25 block numbers
Definition at line 367 of file Atlas.cpp.
References getBlockCrc(), m_mapDefinitions, MapDefinition::mapHeightInTiles, MapDefinition::mapWidthInTiles, MapDefinition::mapWrapHeightInTiles, and MapDefinition::mapWrapWidthInTiles.
Referenced by onHashQuery().
Initialize()
bool Atlas::Initialize () static
Initializes Atlas class. Gets pointers to the client global pointer and subscribes to packets.
Returns
true on success
Definition at line 48 of file Atlas.cpp.
References Logger::g_pLogger, UltimaLive::g_pUltimaLive, Logger::LogPrint(), Logger::LogPrintError(), UltimaLive::Lookup(), m_pClient, m_pFileManager, m_pNetworkManager, onBeforeMapChange(), onHashQuery(), onLogout(), onMapChange(), onRefreshClientView(), onShardIdentifierUpdate(), onUpdateLand(), onUpdateMapDefinitions(), onUpdateStatics(), NetworkManager::subscribeToBlockQueryRequest(), NetworkManager::subscribeToLandUpdate(), NetworkManager::subscribeToLogout(), NetworkManager::subscribeToMapDefinitionUpdate(), NetworkManager::subscribeToOnBeforeMapChange(), NetworkManager::subscribeToOnMapChange(), NetworkManager::subscribeToRefreshClient(), NetworkManager::subscribeToStaticsUpdate(), and NetworkManager::subscribeToUltimaLiveLoginComplete().
LoadMap()
void Atlas::LoadMap (uint8_t map)
Loads a map based on map number.
Parameters
map Map Number
Definition at line 142 of file Atlas.cpp.
References Logger::g_pLogger, BaseFileManager::InitializeShardMaps(), BaseFileManager::LoadMap(), Logger::LogPrint(), m_currentMap, m_firstMapLoad, m_mapDefinitions, m_pClient, m_pFileManager, m_shardIdentifier, and Client::SetMapDimensions().
Referenced by onMapChange().
onHashQuery()
void Atlas::onHashQuery (uint32_t blockNumber, uint8_t mapNumber) protected
Responds to a server hash query for a particular map block (land and statics)
Parameters
blockNumber Map Block Number
mapNumber Map Number
Definition at line 212 of file Atlas.cpp.
References Logger::g_pLogger, GetGroupOfBlockCrcs(), Logger::LogPrint(), m_pNetworkManager, and NetworkManager::sendPacketToServer().
Referenced by Initialize().
onMapChange()
void Atlas::onMapChange (uint8_t & rMap) protected
Loads the specified map.
Parameters
rMap Map number to load
Definition at line 305 of file Atlas.cpp.
References LoadMap().
Referenced by Initialize().
onShardIdentifierUpdate()
void Atlas::onShardIdentifierUpdate (std::string shardIdentifier) protected
setter for Shard Identifier
Parameters
shardIdentifier
Definition at line 124 of file Atlas.cpp.
References m_shardIdentifier.
Referenced by Initialize().
onUpdateLand()
void Atlas::onUpdateLand (uint8_t mapNumber, uint32_t blockNumber, uint8_t * pLandData) protected
@ Updates a land block on a given map
Parameters
mapNumber Map Number
blockNumber Land Block Number
pLandData Pointer to the new land data which is of fixed size
Definition at line 200 of file Atlas.cpp.
References m_pClient, m_pFileManager, Client::refreshClientLand(), and BaseFileManager::updateLandBlock().
Referenced by Initialize().
onUpdateMapDefinitions()
void Atlas::onUpdateMapDefinitions (std::vector< MapDefinition > definitions) protected
Updates map definitions as received from the server.
Parameters
definitions New map definitions
Definition at line 248 of file Atlas.cpp.
References Logger::g_pLogger, Logger::LogPrint(), and m_mapDefinitions.
Referenced by Initialize().
onUpdateStatics()
void Atlas::onUpdateStatics (uint8_t mapNumber, uint32_t blockNumber, uint8_t * pData, uint32_t length) protected
Updates a static block by calling the filemanager and then refreshes the client.
Parameters
mapNumber Map Number
blockNumber Statics Block Number
pData Pointer to the new memory block containing the statics data
length Length of the new memory block
Definition at line 186 of file Atlas.cpp.
References Logger::g_pLogger, Logger::LogPrint(), m_pClient, m_pFileManager, Client::refreshClientStatics(), and BaseFileManager::writeStaticsBlock().
Referenced by Initialize().
The documentation for this class was generated from the following files:
UltimaLive/Maps/Atlas.h
UltimaLive/Maps/Atlas.cpp