UltimaLive: LoginHandler Class Reference
LoginHandler Class Reference
Handles the Ultima Client's Login.
#include <LoginHandler.h>
Public Member Functions
LoginHandler ()
LoginHandler constructor.
Static Public Member Functions
static bool Initialize ()
Self Registering Class Initialize function that sets up packet subscriptions with the network manager.
static void Configure ()
Self Registering Class Configure function that registeres this class with the UltimaLive application state.
Private Member Functions
void onLogoutRequest ()
Cleans up when the client receives a logout request.
void onLoginConfirm (uint8_t *pPacketData)
Handles the login confirmation packet sent from the server. Caches the packet to be used to complete login in the proper order.
void onLoginComplete ()
Sends the UltimaLive message to the client when the login confirmation packet has been received.
void onBeforeMapChange (uint8_t &rMap)
This function is called each time that the server changes which map the client is on.
void onServerMobileUpdate ()
This function is called when the server sends its mobile update to the client. This functions performs a refresh client prior to the client receiving its first update. This only happens once.
void onUpdateMapDefinitions (std::vector< MapDefinition > definitions)
This function is called when the server sends map definitions to the client. It is responsible for setting the first mobile update flag.
Private Attributes
NetworkManager * m_pManager
Pointer to the concrete network manager.
bool m_needToSendCachedLoginPacket
Flag indicating whether or not to send a cached login packet as part of the login process.
bool m_firstHashQuery
Flag indicating if the first hash query has been made.
uint8_t * m_pCachedLoginPacket
Pointer to the cached login packet.
bool m_firstMobileUpdateFromServer
Flag indicating if the first mobile update has been sent from the server.
Static Private Attributes
static SelfRegisteringClass< LoginHandler > m_registration
Self registering class variable which triggers the self registration.
Detailed Description
Handles the Ultima Client's Login.
Definition at line 45 of file LoginHandler.h.
Member Function Documentation
onLoginConfirm()
void LoginHandler::onLoginConfirm (uint8_t * pPacketData) private
Handles the login confirmation packet sent from the server. Caches the packet to be used to complete login in the proper order.
Parameters
pPacketData pointer to the packet data
Definition at line 143 of file LoginHandler.cpp.
References Logger::g_pLogger, Logger::LogPrint(), and m_pCachedLoginPacket.
Referenced by Initialize().
onUpdateMapDefinitions()
void LoginHandler::onUpdateMapDefinitions (std::vector< MapDefinition > definitions) private
This function is called when the server sends map definitions to the client. It is responsible for setting the first mobile update flag.
Parameters
definitions Vector of MapDefinitions received from the server
Definition at line 101 of file LoginHandler.cpp.
References m_firstMobileUpdateFromServer.
Referenced by Initialize().
The documentation for this class was generated from the following files:
UltimaLive/LoginHandler.h
UltimaLive/LoginHandler.cpp